/* GENERATED by scripts/kit-extract.ts from docs/source/STCUIAnalytics.html.
 *
 * Do not edit. Run `npm run kit:extract` when a new kit arrives, and
 * commit the result: `npm run check:kit` regenerates it and fails if
 * this file has drifted from the kit.
 *
 * These are the kit's own inline styles, read back out of the rendered
 * page. Analytics components import them so that no analytics component
 * has to contain a number, which is the only reliable way to stop one
 * being invented. */

export const KIT_COLOURS = {
  "STC": "#09163A",
  "Trailer sales": "#3D5290",
  "Rentals": "#8492C0",
  "Leads": "#D9DEEC",
  "Quoted": "#8492C0",
  "On hire": "#09163A",
  "Workshop": "#8492C0",
  "Idle": "#EFEFEC",
  "Silver": "#C4BFBC",
  "Gold": "#E0C63F",
  "Platinum": "#09163A"
} as const;

export const KIT_RAMPS = {
  "cohort": {
    "rgb": "9,22,58",
    "stops": [
      0.15,
      0.32,
      0.49,
      0.66,
      0.83,
      1
    ],
    "from": 70,
    "to": 100
  }
} as const;

export const KIT_DEVICES = {
  "cohort": {
    "title": "Contract retention by start month",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:20px 22px;display:flex;flex-direction:column;gap:14px",
      "kids": [
        {
          "tag": "div",
          "style": "display:flex;flex-direction:column;gap:4px",
          "kids": [
            {
              "tag": "span",
              "style": "font-family:var(--panton);font-weight:700;font-size:14px",
              "text": "Contract retention by start month"
            },
            {
              "tag": "span",
              "style": "display:block;font-size:12px;line-height:1.45;color:var(--text-subtle);font-style:italic",
              "text": "Everything signed since April is still live. The two lapses both came from the January cohort."
            }
          ]
        },
        {
          "tag": "div",
          "kids": [
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "SIGNED"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M0"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M1"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M2"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M3"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M4"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M5"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M6"
                },
                {
                  "tag": "span",
                  "style": "flex:1;text-align:center;font-size:9.5px;font-weight:700;letter-spacing:.06em;color:var(--text-subtle)",
                  "text": "M7"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "January"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "14"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.80);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "93"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.80);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "93"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.60);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "86"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.60);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "86"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.60);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "86"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.41);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "79"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.41);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "79"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "February"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "11"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.74);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "91"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.74);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "91"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.74);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "91"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.74);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "91"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.74);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "91"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "March"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "13"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.77);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "92"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.77);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "92"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,0.77);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "92"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "April"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "9"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "May"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "12"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "June"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "10"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "July"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "15"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:3px;margin-bottom:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "flex:none;width:104px;display:flex;align-items:center;font-size:11.5px;font-weight:600",
                  "text": "August"
                },
                {
                  "tag": "span",
                  "style": "flex:none;width:44px;display:flex;align-items:center;justify-content:center;font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;background:var(--bg-subtle);height:30px",
                  "text": "12"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:rgba(9,22,58,1.00);display:flex;align-items:center;justify-content:center;font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums;color:#fff",
                  "text": "100"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                },
                {
                  "tag": "span",
                  "style": "flex:1;height:30px;background:var(--bg-subtle);border:1px dashed var(--border)"
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "border-top:1px solid var(--border);padding-top:12px;display:flex;align-items:center;gap:16px",
          "kids": [
            {
              "tag": "span",
              "style": "flex:1;font-size:12px;color:var(--text-subtle);line-height:1.45",
              "text": "Dashed cells are months that have not happened yet, not missing data. Retention is contracts still live, not value."
            },
            {
              "tag": "span",
              "style": "display:inline-flex;align-items:center;gap:7px;font-size:11px;color:var(--text-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:flex",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:15px;height:12px;background:rgba(9,22,58,0.15)"
                    },
                    {
                      "tag": "span",
                      "style": "width:15px;height:12px;background:rgba(9,22,58,0.32)"
                    },
                    {
                      "tag": "span",
                      "style": "width:15px;height:12px;background:rgba(9,22,58,0.49)"
                    },
                    {
                      "tag": "span",
                      "style": "width:15px;height:12px;background:rgba(9,22,58,0.66)"
                    },
                    {
                      "tag": "span",
                      "style": "width:15px;height:12px;background:rgba(9,22,58,0.83)"
                    },
                    {
                      "tag": "span",
                      "style": "width:15px;height:12px;background:rgba(9,22,58,1)"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "tierStack": {
    "title": "Weekly contracted value",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:20px 22px;display:flex;flex-direction:column;gap:14px",
      "kids": [
        {
          "tag": "div",
          "style": "display:flex;align-items:flex-start;justify-content:space-between;gap:16px",
          "kids": [
            {
              "tag": "div",
              "style": "display:flex;flex-direction:column;gap:4px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:700;font-size:14px",
                  "text": "Weekly contracted value"
                },
                {
                  "tag": "span",
                  "style": "display:block;font-size:12px;line-height:1.45;color:var(--text-subtle);font-style:italic",
                  "text": "The book is up 62% since January, and almost all of that growth is Gold."
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:12px;flex-wrap:wrap",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:11px;height:11px;background:#C4BFBC"
                    }
                  ]
                },
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:11px;height:11px;background:#E0C63F"
                    }
                  ]
                },
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:11px;height:11px;background:#09163A"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "svg",
          "style": "width:100%;height:200px;display:block",
          "kids": [
            {
              "tag": "line"
            },
            {
              "tag": "line"
            },
            {
              "tag": "line"
            },
            {
              "tag": "line"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            },
            {
              "tag": "rect"
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;margin-top:7px",
          "kids": [
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Jan"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£3.6k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Feb"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£4.1k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Mar"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£4.6k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Apr"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£5.2k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "May"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£5.8k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Jun"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£6.3k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Jul"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£6.8k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Aug"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:500;font-variant-numeric:tabular-nums",
                  "text": "£7.3k"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:10.5px;color:var(--text-subtle)",
                  "text": "Sep"
                },
                {
                  "tag": "span",
                  "style": "font-size:10.5px;font-weight:700;font-variant-numeric:tabular-nums",
                  "text": "£7.8k"
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;gap:0;border-top:1px solid var(--border);padding-top:14px",
          "kids": [
            {
              "tag": "div",
              "style": "flex:1;padding:0 18px;padding-left:0;display:flex;flex-direction:column;gap:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:700;font-size:9.5px;letter-spacing:.14em;color:var(--text-subtle)",
                  "text": "THIS WEEK"
                },
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:800;font-size:20px;letter-spacing:-0.02em;font-variant-numeric:tabular-nums",
                  "text": "£7,830"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle)",
                  "text": "across 96 contracts"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;padding:0 18px;border-left:1px solid var(--border);display:flex;flex-direction:column;gap:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:700;font-size:9.5px;letter-spacing:.14em;color:var(--text-subtle)",
                  "text": "ANNUALISED"
                },
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:800;font-size:20px;letter-spacing:-0.02em;font-variant-numeric:tabular-nums",
                  "text": "£407k"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle)",
                  "text": "if nothing changes"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;padding:0 18px;border-left:1px solid var(--border);display:flex;flex-direction:column;gap:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:700;font-size:9.5px;letter-spacing:.14em;color:var(--text-subtle)",
                  "text": "ADDED IN SEPT"
                },
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:800;font-size:20px;letter-spacing:-0.02em;font-variant-numeric:tabular-nums",
                  "text": "£590"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle)",
                  "text": "9 new contracts"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;padding:0 18px;border-left:1px solid var(--border);display:flex;flex-direction:column;gap:3px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:700;font-size:9.5px;letter-spacing:.14em;color:var(--text-subtle)",
                  "text": "AVERAGE"
                },
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:800;font-size:20px;letter-spacing:-0.02em;font-variant-numeric:tabular-nums",
                  "text": "£82"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle)",
                  "text": "per contract per week"
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "bullet": {
    "title": "Month to date against target",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:20px 22px;display:flex;flex-direction:column;gap:14px",
      "kids": [
        {
          "tag": "div",
          "style": "display:flex;align-items:center;justify-content:space-between",
          "kids": [
            {
              "tag": "span",
              "style": "font-family:var(--panton);font-weight:700;font-size:14px",
              "text": "Month to date against target"
            },
            {
              "tag": "span",
              "style": "display:inline-flex;align-items:center;gap:8px;font-size:11.5px;color:var(--text-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "width:2px;height:14px;background:var(--accent)"
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:14px",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:126px;font-size:12.5px;font-weight:600",
              "text": "STC maintenance"
            },
            {
              "tag": "span",
              "style": "flex:1;position:relative;height:26px;background:var(--bg-subtle);min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:80.3%;background:#09163A"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:78.1%;top:-4px;bottom:-4px;width:2px;background:var(--accent)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:82px;text-align:right;font-family:var(--panton);font-weight:800;font-size:15px;font-variant-numeric:tabular-nums",
              "text": "£1284k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:74px;text-align:right;font-size:11.5px;color:var(--success);font-weight:600",
              "text": "+34k"
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:14px",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:126px;font-size:12.5px;font-weight:600",
              "text": "Trailer sales"
            },
            {
              "tag": "span",
              "style": "flex:1;position:relative;height:26px;background:var(--bg-subtle);min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:43.9%;background:#3D5290"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:35.0%;top:-4px;bottom:-4px;width:2px;background:var(--accent)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:82px;text-align:right;font-family:var(--panton);font-weight:800;font-size:15px;font-variant-numeric:tabular-nums",
              "text": "£702k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:74px;text-align:right;font-size:11.5px;color:var(--success);font-weight:600",
              "text": "+142k"
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:14px",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:126px;font-size:12.5px;font-weight:600",
              "text": "Rentals"
            },
            {
              "tag": "span",
              "style": "flex:1;position:relative;height:26px;background:var(--bg-subtle);min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:9.1%;background:#8492C0"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:13.1%;top:-4px;bottom:-4px;width:2px;background:var(--accent)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:82px;text-align:right;font-family:var(--panton);font-weight:800;font-size:15px;font-variant-numeric:tabular-nums",
              "text": "£146k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:74px;text-align:right;font-size:11.5px;color:var(--danger);font-weight:600",
              "text": "-64k"
            }
          ]
        },
        {
          "tag": "div",
          "style": "border-top:1px solid var(--border);padding-top:14px;display:flex;align-items:center;gap:14px",
          "kids": [
            {
              "tag": "span",
              "style": "font-family:var(--panton);font-weight:800;font-size:15px;width:126px",
              "text": "Group"
            },
            {
              "tag": "span",
              "style": "flex:1;font-size:12.5px;color:var(--text-muted)",
              "text": "Ahead overall, but only because trailer sales beat target by £142k. Rentals is £64k short."
            },
            {
              "tag": "span",
              "style": "font-family:var(--panton);font-weight:800;font-size:17px;font-variant-numeric:tabular-nums",
              "text": "£2,132k"
            },
            {
              "tag": "span",
              "style": "width:74px;text-align:right;font-size:12px;font-weight:600;color:var(--success)",
              "text": "+112k"
            }
          ]
        }
      ]
    }
  },
  "indexed": {
    "title": "Twelve months, indexed",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:20px 22px;display:flex;flex-direction:column;gap:14px",
      "kids": [
        {
          "tag": "div",
          "style": "display:flex;align-items:flex-start;justify-content:space-between;gap:16px",
          "kids": [
            {
              "tag": "div",
              "style": "display:flex;flex-direction:column;gap:4px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-family:var(--panton);font-weight:700;font-size:14px",
                  "text": "Twelve months, indexed"
                },
                {
                  "tag": "span",
                  "style": "display:block;font-size:12px;line-height:1.45;color:var(--text-subtle);font-style:italic",
                  "text": "Trailer sales has grown by half. Rentals is 12% below where it started."
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;gap:14px;flex-wrap:wrap",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11.5px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:14px;height:3px;background:#09163A"
                    }
                  ]
                },
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11.5px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:14px;height:2px;background:#3D5290"
                    }
                  ]
                },
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11.5px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:14px;height:2px;background:#8492C0"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "position:relative",
          "kids": [
            {
              "tag": "svg",
              "style": "width:100%;height:180px;display:block",
              "kids": [
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "polyline"
                },
                {
                  "tag": "polyline"
                },
                {
                  "tag": "polyline"
                }
              ]
            },
            {
              "tag": "span",
              "style": "position:absolute;left:6px;top:41.7%;transform:translateY(-130%);font-size:10.5px;font-weight:600;color:var(--text-subtle);background:var(--surface);padding:0 4px",
              "text": "100 = where each division started"
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;justify-content:space-between",
          "kids": [
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "S"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "O"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "N"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "D"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "J"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "F"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "M"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "A"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "M"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "J"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "J"
            },
            {
              "tag": "span",
              "style": "font-size:10px;color:var(--text-subtle)",
              "text": "A"
            }
          ]
        },
        {
          "tag": "div",
          "style": "border-top:1px solid var(--border);padding-top:12px",
          "kids": [
            {
              "tag": "span",
              "style": "font-size:12px;color:var(--text-subtle);line-height:1.45",
              "text": "Indexing hides the size of each division on purpose. Use it for direction, and the revenue bars above for weight."
            }
          ]
        }
      ]
    }
  },
  "waterfall": {
    "title": "August close to September month to date",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:20px 22px;display:flex;flex-direction:column;gap:14px",
      "kids": [
        {
          "tag": "div",
          "style": "display:flex;flex-direction:column;gap:4px",
          "kids": [
            {
              "tag": "span",
              "style": "font-family:var(--panton);font-weight:700;font-size:14px",
              "text": "August close to September month to date"
            },
            {
              "tag": "span",
              "style": "display:block;font-size:12px;line-height:1.45;color:var(--text-subtle);font-style:italic",
              "text": "Up £290k. Trailer sales added £142k of that, rentals gave £38k back."
            }
          ]
        },
        {
          "tag": "div",
          "kids": [
            {
              "tag": "svg",
              "style": "width:100%;height:180px;display:block",
              "kids": [
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "rect"
                },
                {
                  "tag": "rect"
                },
                {
                  "tag": "rect"
                },
                {
                  "tag": "rect"
                },
                {
                  "tag": "rect"
                }
              ]
            },
            {
              "tag": "div",
              "style": "display:flex;margin-top:8px",
              "kids": [
                {
                  "tag": "div",
                  "style": "flex:1;display:flex;flex-direction:column;align-items:center;gap:2px",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "font-size:11.5px;font-weight:600",
                      "text": "Aug close"
                    },
                    {
                      "tag": "span",
                      "style": "font-size:11px;font-variant-numeric:tabular-nums;font-weight:700;color:var(--text)",
                      "text": "£1842k"
                    }
                  ]
                },
                {
                  "tag": "div",
                  "style": "flex:1;display:flex;flex-direction:column;align-items:center;gap:2px",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "font-size:11.5px;font-weight:600",
                      "text": "STC"
                    },
                    {
                      "tag": "span",
                      "style": "font-size:11px;font-variant-numeric:tabular-nums;font-weight:600;color:var(--success)",
                      "text": "+186k"
                    }
                  ]
                },
                {
                  "tag": "div",
                  "style": "flex:1;display:flex;flex-direction:column;align-items:center;gap:2px",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "font-size:11.5px;font-weight:600",
                      "text": "Trailer"
                    },
                    {
                      "tag": "span",
                      "style": "font-size:11px;font-variant-numeric:tabular-nums;font-weight:600;color:var(--success)",
                      "text": "+142k"
                    }
                  ]
                },
                {
                  "tag": "div",
                  "style": "flex:1;display:flex;flex-direction:column;align-items:center;gap:2px",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "font-size:11.5px;font-weight:600",
                      "text": "Rentals"
                    },
                    {
                      "tag": "span",
                      "style": "font-size:11px;font-variant-numeric:tabular-nums;font-weight:600;color:var(--danger)",
                      "text": "-38k"
                    }
                  ]
                },
                {
                  "tag": "div",
                  "style": "flex:1;display:flex;flex-direction:column;align-items:center;gap:2px",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "font-size:11.5px;font-weight:600",
                      "text": "Sep MTD"
                    },
                    {
                      "tag": "span",
                      "style": "font-size:11px;font-variant-numeric:tabular-nums;font-weight:700;color:var(--text)",
                      "text": "£2132k"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "leaderboard": {
    "title": "September, new business by person",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);overflow:hidden",
      "kids": [
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:14px;padding:12px 16px;border-bottom:1px solid var(--border);background:var(--bg-subtle)",
          "kids": [
            {
              "tag": "span",
              "style": "flex:1;font-family:var(--panton);font-weight:700;font-size:14px",
              "text": "September, new business by person"
            },
            {
              "tag": "div",
              "style": "display:flex;gap:14px",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:11px;height:11px;background:#D9DEEC"
                    }
                  ]
                },
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:11px;height:11px;background:#8492C0"
                    }
                  ]
                },
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--text-muted)",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:11px;height:11px;background:var(--navy-900)"
                    }
                  ]
                }
              ]
            },
            {
              "tag": "span",
              "style": "display:inline-flex;align-items:center;gap:7px;font-size:11.5px;color:var(--text-subtle);cursor:pointer;font-weight:600",
              "kids": [
                {
                  "tag": "svg",
                  "style": "flex:none",
                  "kids": [
                    {
                      "tag": "path"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:10px;padding:11px 16px;",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:20px;font-family:var(--panton);font-weight:800;font-size:13px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
              "text": "1"
            },
            {
              "tag": "span",
              "style": "flex:none;width:28px;height:28px;border-radius:999px;background:var(--bg-subtle);color:var(--text-muted);display:inline-flex;align-items:center;justify-content:center;font-family:var(--panton);font-weight:700;font-size:11px;letter-spacing:0;border:1px solid var(--border);",
              "text": "DM"
            },
            {
              "tag": "span",
              "style": "flex:none;width:104px;min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;font-size:13px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis",
                  "text": "Dean Mann"
                },
                {
                  "tag": "span",
                  "style": "display:block;font-size:10.5px;color:var(--text-subtle)",
                  "text": "Trailer sales"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;height:19px;padding:0 8px;border:1px solid #3D5290;color:#3D5290;border-radius:var(--r-sm);font-size:10px;font-weight:700;letter-spacing:.08em;white-space:nowrap",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:6px;height:6px;background:currentColor"
                    }
                  ]
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:1;min-width:90px;position:relative;height:22px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:82.9%;background:#D9DEEC"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:63.4%;background:#8492C0"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:43.9%;background:var(--navy-900)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:96px;display:flex;gap:8px;justify-content:flex-end;font-variant-numeric:tabular-nums",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle)",
                  "text": "34"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-muted)",
                  "text": "26"
                },
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:700",
                  "text": "18"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:72px;text-align:right;font-family:var(--panton);font-weight:800;font-size:14px;font-variant-numeric:tabular-nums",
              "text": "£412k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:44px;text-align:right",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:3px;font-size:12px;font-weight:700;color:var(--success)",
                  "kids": [
                    {
                      "tag": "svg",
                      "style": "flex:none",
                      "kids": [
                        {
                          "tag": "path"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:10px;padding:11px 16px;border-top:1px solid var(--border);",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:20px;font-family:var(--panton);font-weight:800;font-size:13px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
              "text": "2"
            },
            {
              "tag": "span",
              "style": "flex:none;width:28px;height:28px;border-radius:999px;background:var(--bg-subtle);color:var(--text-muted);display:inline-flex;align-items:center;justify-content:center;font-family:var(--panton);font-weight:700;font-size:11px;letter-spacing:0;border:1px solid var(--border);",
              "text": "TP"
            },
            {
              "tag": "span",
              "style": "flex:none;width:104px;min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;font-size:13px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis",
                  "text": "Tom Price"
                },
                {
                  "tag": "span",
                  "style": "display:block;font-size:10.5px;color:var(--text-subtle)",
                  "text": "FleetSmart+"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;height:19px;padding:0 8px;border:1px solid #09163A;color:#09163A;border-radius:var(--r-sm);font-size:10px;font-weight:700;letter-spacing:.08em;white-space:nowrap",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:6px;height:6px;background:currentColor"
                    }
                  ]
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:1;min-width:90px;position:relative;height:22px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:100.0%;background:#D9DEEC"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:75.6%;background:#8492C0"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:41.5%;background:var(--navy-900)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:96px;display:flex;gap:8px;justify-content:flex-end;font-variant-numeric:tabular-nums",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle)",
                  "text": "41"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-muted)",
                  "text": "31"
                },
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:700",
                  "text": "17"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:72px;text-align:right;font-family:var(--panton);font-weight:800;font-size:14px;font-variant-numeric:tabular-nums",
              "text": "£186k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:44px;text-align:right",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:3px;font-size:12px;font-weight:700;color:var(--success)",
                  "kids": [
                    {
                      "tag": "svg",
                      "style": "flex:none",
                      "kids": [
                        {
                          "tag": "path"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:10px;padding:11px 16px;border-top:1px solid var(--border);",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:20px;font-family:var(--panton);font-weight:800;font-size:13px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
              "text": "3"
            },
            {
              "tag": "span",
              "style": "flex:none;width:28px;height:28px;border-radius:999px;background:var(--bg-subtle);color:var(--text-muted);display:inline-flex;align-items:center;justify-content:center;font-family:var(--panton);font-weight:700;font-size:11px;letter-spacing:0;border:1px solid var(--border);",
              "text": "RL"
            },
            {
              "tag": "span",
              "style": "flex:none;width:104px;min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;font-size:13px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis",
                  "text": "Rob Latham"
                },
                {
                  "tag": "span",
                  "style": "display:block;font-size:10.5px;color:var(--text-subtle)",
                  "text": "STC service"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;height:19px;padding:0 8px;border:1px solid #09163A;color:#09163A;border-radius:var(--r-sm);font-size:10px;font-weight:700;letter-spacing:.08em;white-space:nowrap",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:6px;height:6px;background:currentColor"
                    }
                  ]
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:1;min-width:90px;position:relative;height:22px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:68.3%;background:#D9DEEC"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:46.3%;background:#8492C0"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:29.3%;background:var(--navy-900)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:96px;display:flex;gap:8px;justify-content:flex-end;font-variant-numeric:tabular-nums",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle)",
                  "text": "28"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-muted)",
                  "text": "19"
                },
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:700",
                  "text": "12"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:72px;text-align:right;font-family:var(--panton);font-weight:800;font-size:14px;font-variant-numeric:tabular-nums",
              "text": "£94k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:44px;text-align:right",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:3px;font-size:12px;font-weight:700;color:var(--danger)",
                  "kids": [
                    {
                      "tag": "svg",
                      "style": "flex:none",
                      "kids": [
                        {
                          "tag": "path"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:10px;padding:11px 16px;border-top:1px solid var(--border);",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:20px;font-family:var(--panton);font-weight:800;font-size:13px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
              "text": "4"
            },
            {
              "tag": "span",
              "style": "flex:none;width:28px;height:28px;border-radius:999px;background:var(--bg-subtle);color:var(--text-muted);display:inline-flex;align-items:center;justify-content:center;font-family:var(--panton);font-weight:700;font-size:11px;letter-spacing:0;border:1px solid var(--border);",
              "text": "SK"
            },
            {
              "tag": "span",
              "style": "flex:none;width:104px;min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;font-size:13px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis",
                  "text": "Sam Keane"
                },
                {
                  "tag": "span",
                  "style": "display:block;font-size:10.5px;color:var(--text-subtle)",
                  "text": "Rentals"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;height:19px;padding:0 8px;border:1px solid #8492C0;color:#8492C0;border-radius:var(--r-sm);font-size:10px;font-weight:700;letter-spacing:.08em;white-space:nowrap",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:6px;height:6px;background:currentColor"
                    }
                  ]
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:1;min-width:90px;position:relative;height:22px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:53.7%;background:#D9DEEC"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:34.1%;background:#8492C0"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:14.6%;background:var(--navy-900)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:96px;display:flex;gap:8px;justify-content:flex-end;font-variant-numeric:tabular-nums",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle)",
                  "text": "22"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-muted)",
                  "text": "14"
                },
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:700",
                  "text": "6"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:72px;text-align:right;font-family:var(--panton);font-weight:800;font-size:14px;font-variant-numeric:tabular-nums",
              "text": "£38k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:44px;text-align:right",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:3px;font-size:12px;font-weight:700;color:var(--danger)",
                  "kids": [
                    {
                      "tag": "svg",
                      "style": "flex:none",
                      "kids": [
                        {
                          "tag": "path"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:10px;padding:11px 16px;border-top:1px solid var(--border);",
          "kids": [
            {
              "tag": "span",
              "style": "flex:none;width:20px;font-family:var(--panton);font-weight:800;font-size:13px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
              "text": "5"
            },
            {
              "tag": "span",
              "style": "flex:none;width:28px;height:28px;border-radius:999px;background:var(--bg-subtle);color:var(--text-muted);display:inline-flex;align-items:center;justify-content:center;font-family:var(--panton);font-weight:700;font-size:11px;letter-spacing:0;border:1px solid var(--border);",
              "text": "JH"
            },
            {
              "tag": "span",
              "style": "flex:none;width:104px;min-width:0",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;font-size:13px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis",
                  "text": "Jo Hartley"
                },
                {
                  "tag": "span",
                  "style": "display:block;font-size:10.5px;color:var(--text-subtle)",
                  "text": "Trailer sales"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:6px;height:19px;padding:0 8px;border:1px solid #3D5290;color:#3D5290;border-radius:var(--r-sm);font-size:10px;font-weight:700;letter-spacing:.08em;white-space:nowrap",
                  "kids": [
                    {
                      "tag": "span",
                      "style": "width:6px;height:6px;background:currentColor"
                    }
                  ]
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:1;min-width:90px;position:relative;height:22px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:41.5%;background:#D9DEEC"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:26.8%;background:#8492C0"
                },
                {
                  "tag": "span",
                  "style": "position:absolute;left:0;top:0;bottom:0;width:17.1%;background:var(--navy-900)"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:96px;display:flex;gap:8px;justify-content:flex-end;font-variant-numeric:tabular-nums",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle)",
                  "text": "17"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-muted)",
                  "text": "11"
                },
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:700",
                  "text": "7"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:72px;text-align:right;font-family:var(--panton);font-weight:800;font-size:14px;font-variant-numeric:tabular-nums",
              "text": "£96k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:44px;text-align:right",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:inline-flex;align-items:center;gap:3px;font-size:12px;font-weight:700;color:var(--success)",
                  "kids": [
                    {
                      "tag": "svg",
                      "style": "flex:none",
                      "kids": [
                        {
                          "tag": "path"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;align-items:center;gap:10px;padding:11px 16px;border-top:2px solid var(--border-emphasis);background:var(--bg-subtle)",
          "kids": [
            {
              "tag": "span",
              "style": "flex:1;font-size:12.5px;font-weight:700;padding-left:34px",
              "text": "Total"
            },
            {
              "tag": "span",
              "style": "flex:none;width:96px;display:flex;gap:8px;justify-content:flex-end;font-variant-numeric:tabular-nums",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle)",
                  "text": "142"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-muted)",
                  "text": "101"
                },
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:700",
                  "text": "60"
                }
              ]
            },
            {
              "tag": "span",
              "style": "flex:none;width:72px;text-align:right;font-family:var(--panton);font-weight:800;font-size:14px;font-variant-numeric:tabular-nums",
              "text": "£826k"
            },
            {
              "tag": "span",
              "style": "flex:none;width:44px"
            }
          ]
        }
      ]
    }
  },
  "dotplot": {
    "title": "Lead to won conversion",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:20px 22px;display:flex;flex-direction:column;gap:12px",
      "kids": [
        {
          "tag": "div",
          "style": "display:flex;flex-direction:column;gap:4px",
          "kids": [
            {
              "tag": "span",
              "style": "font-family:var(--panton);font-weight:700;font-size:14px",
              "text": "Lead to won conversion"
            },
            {
              "tag": "span",
              "style": "display:block;font-size:12px;line-height:1.45;color:var(--text-subtle);font-style:italic",
              "text": "Group average is 42%. Dean is above it on the biggest book, Sam is well below on the smallest."
            }
          ]
        },
        {
          "tag": "div",
          "style": "position:relative",
          "kids": [
            {
              "tag": "svg",
              "style": "width:100%;height:150px;display:block;overflow:visible",
              "kids": [
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "line"
                },
                {
                  "tag": "circle"
                },
                {
                  "tag": "circle"
                },
                {
                  "tag": "circle"
                },
                {
                  "tag": "circle"
                },
                {
                  "tag": "circle"
                }
              ]
            },
            {
              "tag": "span",
              "style": "position:absolute;right:4px;top:40.0%;transform:translateY(-125%);font-size:10.5px;font-weight:700;color:var(--accent);background:var(--surface);padding:0 4px",
              "text": "group 42%"
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;margin-top:8px",
          "kids": [
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:11.5px;font-weight:600",
                  "text": "DM"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "53%"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:11.5px;font-weight:600",
                  "text": "TP"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "41%"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:11.5px;font-weight:600",
                  "text": "RL"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "43%"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:11.5px;font-weight:600",
                  "text": "SK"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "27%"
                }
              ]
            },
            {
              "tag": "div",
              "style": "flex:1;text-align:center;display:flex;flex-direction:column;gap:1px",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:11.5px;font-weight:600",
                  "text": "JH"
                },
                {
                  "tag": "span",
                  "style": "font-size:11px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "41%"
                }
              ]
            }
          ]
        },
        {
          "tag": "span",
          "style": "font-size:12px;color:var(--text-subtle);line-height:1.45;border-top:1px solid var(--border);padding-top:11px",
          "text": "Dot size is won value, so a small dot high up is a good rate on a small book. Both matter, and neither alone tells you w"
        }
      ]
    }
  },
  "sourceFlow": {
    "title": "Where leads came from, and what became of them",
    "found": true,
    "node": {
      "tag": "div",
      "style": "display:flex;flex-direction:column;gap:3px",
      "kids": [
        {
          "tag": "span",
          "style": "font-family:var(--panton);font-weight:700;font-size:15px;letter-spacing:-0.02em",
          "text": "Where leads came from, and what became of them"
        },
        {
          "tag": "span",
          "style": "font-size:12.5px;color:var(--text-subtle);line-height:1.45;max-width:80ch",
          "text": "Bands from each source splitting into won by division and lost. The loss is drawn at full width rather than left as the "
        }
      ]
    }
  },
  "scatter": {
    "title": "Stock age against margin",
    "found": true,
    "node": {
      "tag": "div",
      "style": "display:flex;flex-direction:column;gap:3px",
      "kids": [
        {
          "tag": "span",
          "style": "font-family:var(--panton);font-weight:700;font-size:15px;letter-spacing:-0.02em",
          "text": "Stock age against margin"
        },
        {
          "tag": "span",
          "style": "font-size:12.5px;color:var(--text-subtle);line-height:1.45;max-width:80ch",
          "text": "Every dot is a trailer in stock. Right means it has been here too long, low means there is little margin left to give aw"
        }
      ]
    }
  },
  "ageing": {
    "title": "Stock ageing bands",
    "found": true,
    "node": {
      "tag": "div",
      "style": "display:flex;flex-direction:column;gap:3px",
      "kids": [
        {
          "tag": "span",
          "style": "font-family:var(--panton);font-weight:700;font-size:15px;letter-spacing:-0.02em",
          "text": "Stock ageing bands"
        },
        {
          "tag": "span",
          "style": "font-size:12.5px;color:var(--text-subtle);line-height:1.45;max-width:80ch",
          "text": "How the 41 break down, and what each band is worth. The band, not the average, is what tells you whether stock is turnin"
        }
      ]
    }
  },
  "mix": {
    "title": "Mix today, 96 contracts",
    "found": true,
    "node": {
      "tag": "div",
      "style": "background:var(--surface);border:1px solid var(--border);border-radius:var(--r-md);padding:18px 20px;display:flex;flex-direction:column;gap:14px",
      "kids": [
        {
          "tag": "span",
          "style": "font-family:var(--panton);font-weight:700;font-size:13.5px",
          "text": "Mix today, 96 contracts"
        },
        {
          "tag": "div",
          "style": "display:flex;flex-direction:column;gap:6px",
          "kids": [
            {
              "tag": "div",
              "style": "display:flex;justify-content:space-between;align-items:baseline",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:600",
                  "text": "Silver"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "31 · £1,470/wk"
                }
              ]
            },
            {
              "tag": "span",
              "style": "display:block;height:14px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;width:32.3%;height:14px;background:#C4BFBC"
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;flex-direction:column;gap:6px",
          "kids": [
            {
              "tag": "div",
              "style": "display:flex;justify-content:space-between;align-items:baseline",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:600",
                  "text": "Gold"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "48 · £4,620/wk"
                }
              ]
            },
            {
              "tag": "span",
              "style": "display:block;height:14px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;width:50.0%;height:14px;background:#E0C63F"
                }
              ]
            }
          ]
        },
        {
          "tag": "div",
          "style": "display:flex;flex-direction:column;gap:6px",
          "kids": [
            {
              "tag": "div",
              "style": "display:flex;justify-content:space-between;align-items:baseline",
              "kids": [
                {
                  "tag": "span",
                  "style": "font-size:12.5px;font-weight:600",
                  "text": "Platinum"
                },
                {
                  "tag": "span",
                  "style": "font-size:12px;color:var(--text-subtle);font-variant-numeric:tabular-nums",
                  "text": "17 · £1,740/wk"
                }
              ]
            },
            {
              "tag": "span",
              "style": "display:block;height:14px;background:var(--bg-subtle)",
              "kids": [
                {
                  "tag": "span",
                  "style": "display:block;width:17.7%;height:14px;background:#09163A"
                }
              ]
            }
          ]
        },
        {
          "tag": "span",
          "style": "font-size:11.5px;color:var(--text-subtle);line-height:1.45;border-top:1px solid var(--border);padding-top:11px",
          "text": "Gold is half the contracts and 59% of the weekly value. Platinum is 18% of contracts but the highest value each."
        }
      ]
    }
  },
  "verdict": {
    "title": "The month in a sentence",
    "found": false
  }
} as const;
