/* GENERATED by scripts/rate-card-generate.ts from
   docs/source/rate_cards/rate-model.json. Do not edit by hand.
   Run `npm run rate-card:generate` after a new kit arrives.

   ---- Two en dashes in here are deliberate ----

   'Loaded blocks – Trailers' and 'Loaded Weight trailer – Vehicles' are
   row labels copied character for character out of the signed KNDS
   workbook, where they print exactly like that. The repository's dash
   ban governs prose written for this repository; it does not govern a
   customer's document, for the same reason docs/source is exempt from
   it. Rewriting these would change what prints on a rate card a
   customer compares against last year's.

   Every number here came out of the kit. The hours are the signed
   figure divided by its labour pool, at full precision, so that
   hours x pool reproduces the signed card to the penny. See the
   script's header for why the kit's own rounded hours are not used. */

export type RateBasis = 'derived' | 'labour' | 'fixed' | 'statutory' | 'tbc' | 'blank';

/** What each basis means, in the kit's own words. */
export const BASIS_MEANS: Record<RateBasis, string> = {
  "derived": "hours × labour",
  "labour": "the driver",
  "fixed": "flat charge",
  "statutory": "DVSA, never derives",
  "tbc": "not yet priced",
  "blank": "no rate set"
};

/** The five labour rates every derived rate follows. */
export const LABOUR_POOLS: Record<string, number> = {
  "hgv": 85,
  "hgvO": 96,
  "trl": 70,
  "trlO": 83,
  "body": 70
};

export type KitRate = {
  id: string;
  section: string;
  item: string;
  basis: RateBasis;
  pool: string | null;
  /** Which axle columns are priced. Null means the single price column. */
  axles: number[] | null;
  /** Hours per priced column, full precision. Null unless derived. */
  hours: number[] | null;
  /** The signed 2026 figure per priced column. A string is 'tbc' or 'n/a'. */
  signed: (number | string | null)[];
  perAxle: number | null;
  cap: number | null;
  capBy: string | null;
  note: string | null;
};

/** All 45 rates, in the order the master workbook prints them. */
export const KIT_RATES: KitRate[] = [
  {
    "id": "r01",
    "section": "Hourly Rate - Trailers",
    "item": "In hours",
    "basis": "labour",
    "pool": "trl",
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      70,
      70,
      70,
      70
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r02",
    "section": "Hourly Rate - Trailers",
    "item": "Out of Hours",
    "basis": "labour",
    "pool": "trlO",
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      83,
      83,
      83,
      83
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r03",
    "section": "Hourly Rate - HGVs/LCV's",
    "item": "In hours",
    "basis": "labour",
    "pool": "hgv",
    "axles": null,
    "hours": null,
    "signed": [
      85
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r04",
    "section": "Hourly Rate - HGVs/LCV's",
    "item": "Out of Hours",
    "basis": "labour",
    "pool": "hgvO",
    "axles": null,
    "hours": null,
    "signed": [
      96
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r05",
    "section": "Hourly Rate - Bodyshop",
    "item": "In hours",
    "basis": "labour",
    "pool": "body",
    "axles": null,
    "hours": null,
    "signed": [
      70
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r06",
    "section": "Callout/Travel Rates",
    "item": "In hours",
    "basis": "fixed",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      "n/a"
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r07",
    "section": "Callout/Travel Rates",
    "item": "Out of Hours",
    "basis": "fixed",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      50
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r08",
    "section": "Callout/Travel Rates",
    "item": "Mileage Charge",
    "basis": "fixed",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      1.5
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r09",
    "section": "Callout/Travel Rates",
    "item": "C&D",
    "basis": "tbc",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      null
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r10",
    "section": "Service Rates",
    "item": "Trailer Service/Inspection",
    "basis": "derived",
    "pool": "trl",
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": [
      1.2,
      1.2,
      1.2,
      1.2
    ],
    "signed": [
      84,
      84,
      84,
      84
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r11",
    "section": "Service Rates",
    "item": "Van Engine Service (up to 3.5 ton)",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      1.4470588235294117
    ],
    "signed": [
      123
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r12",
    "section": "Service Rates",
    "item": "Van A Service & Inspection (up to 3.5 ton)",
    "basis": "derived",
    "pool": "hgv",
    "axles": [
      2
    ],
    "hours": [
      1.8529411764705883
    ],
    "signed": [
      157.5
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r13",
    "section": "Service Rates",
    "item": "Van B Service & Inspection (up to 3.5 ton)",
    "basis": "tbc",
    "pool": null,
    "axles": [
      2
    ],
    "hours": null,
    "signed": [
      null
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r14",
    "section": "Service Rates",
    "item": "HGV 7.5 ton+ A Service & Inspection",
    "basis": "derived",
    "pool": "hgv",
    "axles": [
      2,
      3
    ],
    "hours": [
      1.8529411764705883,
      2.2411764705882353
    ],
    "signed": [
      157.5,
      190.5
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r15",
    "section": "Service Rates",
    "item": "HGV 7.5 ton+ B Service & Inspection",
    "basis": "derived",
    "pool": "hgv",
    "axles": [
      2,
      3
    ],
    "hours": [
      3.1294117647058823,
      3.376470588235294
    ],
    "signed": [
      266,
      287
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r16",
    "section": "Service Rates",
    "item": "HGV 7.5 ton+ C Service & Inspection",
    "basis": "tbc",
    "pool": null,
    "axles": [
      2,
      3
    ],
    "hours": null,
    "signed": [
      null,
      null
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r17",
    "section": "Service Rates",
    "item": "Digital Tacho",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      1.3625882352941177
    ],
    "signed": [
      115.82
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r18",
    "section": "Service Rates",
    "item": "Smart Tacho",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      1.6125882352941177
    ],
    "signed": [
      137.07
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r19",
    "section": "Service Rates",
    "item": "Tail Lift LOLER & Weight Test (Vehicle)",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      2.070588235294118
    ],
    "signed": [
      176
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r20",
    "section": "Service Rates",
    "item": "Tail Lift LOLER (Vehicle)",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      1.0235294117647058
    ],
    "signed": [
      87
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r21",
    "section": "Service Rates",
    "item": "Weights",
    "basis": "fixed",
    "pool": null,
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      100,
      100,
      100,
      100
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r22",
    "section": "Service Rates",
    "item": "Consumables",
    "basis": "fixed",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      7.9
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r23",
    "section": "Service Rates",
    "item": "Grease & Lubricants",
    "basis": "fixed",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      4.9
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r24",
    "section": "MOT Fees",
    "item": "Submit for MOT at Hyde",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      1.6470588235294117
    ],
    "signed": [
      140
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r25",
    "section": "MOT Fees",
    "item": "Submit for MOT elsewhere",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      1.6470588235294117
    ],
    "signed": [
      140
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r26",
    "section": "MOT Fees",
    "item": "Van Steam Clean",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      0.7647058823529411
    ],
    "signed": [
      65
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r27",
    "section": "MOT Fees",
    "item": "HGV Steam Clean",
    "basis": "derived",
    "pool": "hgv",
    "axles": [
      2,
      3,
      4
    ],
    "hours": [
      1,
      1,
      1
    ],
    "signed": [
      85,
      85,
      85
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r28",
    "section": "MOT Fees",
    "item": "Trailer Steam Clean",
    "basis": "derived",
    "pool": "trl",
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": [
      1.0714285714285714,
      1.0714285714285714,
      1.0714285714285714,
      1.0714285714285714
    ],
    "signed": [
      75,
      75,
      75,
      75
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r29",
    "section": "MOT Fees",
    "item": "Brake Test",
    "basis": "fixed",
    "pool": null,
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      18,
      36,
      54,
      72
    ],
    "perAxle": 18,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r30",
    "section": "MOT Fees",
    "item": "Headlamp Test",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      0.5294117647058824
    ],
    "signed": [
      45
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r31",
    "section": "MOT Fees",
    "item": "Trailer Test Fee",
    "basis": "statutory",
    "pool": null,
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      41,
      54,
      64,
      64
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r32",
    "section": "MOT Fees",
    "item": "Trailer Retest Fee (within 14 days)",
    "basis": "statutory",
    "pool": null,
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      18,
      25,
      33,
      33
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r33",
    "section": "MOT Fees",
    "item": "Trailer Lane Fee",
    "basis": "statutory",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      50
    ],
    "perAxle": null,
    "cap": 50,
    "capBy": "DVSA",
    "note": null
  },
  {
    "id": "r34",
    "section": "MOT Fees",
    "item": "HGV Test Fee",
    "basis": "statutory",
    "pool": null,
    "axles": [
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      91,
      113,
      137
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r35",
    "section": "MOT Fees",
    "item": "HGV Retest Fee (within 14 days)",
    "basis": "statutory",
    "pool": null,
    "axles": [
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      35,
      49,
      65
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r36",
    "section": "MOT Fees",
    "item": "HGV Lane Fee",
    "basis": "statutory",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      70
    ],
    "perAxle": null,
    "cap": 70,
    "capBy": "DVSA",
    "note": null
  },
  {
    "id": "r37",
    "section": "MOT Fees",
    "item": "Loaded blocks – Trailers",
    "basis": "blank",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      null
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r38",
    "section": "MOT Fees",
    "item": "Loaded Weight trailer – Vehicles",
    "basis": "fixed",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      50
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": "Tractors only"
  },
  {
    "id": "r39",
    "section": "MOT Fees",
    "item": "Hire of Weights",
    "basis": "fixed",
    "pool": null,
    "axles": [
      1,
      2,
      3,
      4
    ],
    "hours": null,
    "signed": [
      100,
      100,
      100,
      100
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r40",
    "section": "MOT Fees",
    "item": "Out of area submit for MOT",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      2.823529411764706
    ],
    "signed": [
      240
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r41",
    "section": "MOT Fees",
    "item": "Warm brakes for MOT",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      0.5
    ],
    "signed": [
      42.5
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r42",
    "section": "MOT Fees",
    "item": "Smoke Test",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      0.5882352941176471
    ],
    "signed": [
      50
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r43",
    "section": "Tacho Costs",
    "item": "DTCO Calibration",
    "basis": "derived",
    "pool": "hgv",
    "axles": null,
    "hours": [
      1.3625882352941177
    ],
    "signed": [
      115.82
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r44",
    "section": "Tacho Costs",
    "item": "Buffer Battery",
    "basis": "fixed",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      15.82
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  },
  {
    "id": "r45",
    "section": "Tacho Costs",
    "item": "Submit for Tacho",
    "basis": "blank",
    "pool": null,
    "axles": null,
    "hours": null,
    "signed": [
      null
    ],
    "perAxle": null,
    "cap": null,
    "capBy": null,
    "note": null
  }
];

export const PARTS_MARKUP = [
  {
    "category": "Mechanical Parts",
    "suppliedByCustomer": "%",
    "suppliedBySTC": "£ + %"
  },
  {
    "category": "Tail lift Parts",
    "suppliedByCustomer": "%",
    "suppliedBySTC": "£ + %"
  },
  {
    "category": "Bodywork Parts",
    "suppliedByCustomer": "%",
    "suppliedBySTC": "£ + %"
  }
];

/** The 23 FleetSmart+ inclusions, by tier. */
export const FS_INCLUSIONS = [
  {
    "inclusion": "MOT Inspection",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Laden RBT (vehicles 4/yr, trailers 1/yr, vans n/a)",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "MOT Steamclean",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "MOT Submission",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "MOT Brake Test",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "MOT Smoke Test",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "MOT Test Fee",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "MOT Lane Fee",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Headlamp Alignment",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Weight Hire",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "2 Year Tacho",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Digital compliance storage",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Defect Reporting",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Maintenance Scheduling",
    "silver": true,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "A Service every inspection",
    "silver": false,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "C Service, Annually",
    "silver": false,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Fluid Level Checks",
    "silver": false,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Grease and Lube",
    "silver": false,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Engine Oil Top Up",
    "silver": false,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Bulb Replacement (up to 3 bulbs, excl. H/L & DRL)",
    "silver": false,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Customer compliance portal access",
    "silver": false,
    "gold": true,
    "platinum": true
  },
  {
    "inclusion": "Tail Lift LOLER, Weight Test & Servicing",
    "silver": false,
    "gold": false,
    "platinum": true
  },
  {
    "inclusion": "Brakes & suspension R&M inc",
    "silver": false,
    "gold": false,
    "platinum": true
  }
];
