/* GENERATED BY scripts/order-form-extract.ts. DO NOT EDIT.
 *
 * Read out of docs/source/trailer_sales_order/STC-Trailer-Sales-Order.docx by `npm run orderform:extract`.
 * Every address here was counted by a machine, not by eye, and
 * `npm run check:order-form` asserts the template still agrees.
 */
export const TEMPLATE_PATH = "docs/source/trailer_sales_order/STC-Trailer-Sales-Order.docx";

/** The template this was read from, so a swapped file is noticed. */
export const TEMPLATE_SHA256 = "4eaf762303e4e00706096b3166068d19fb62c427f0c7d1d3f84263250ac9921c";

export type OrderFormSlot = {
  key: string; table: number; row: number; cell: number; label: string;
};

export const SLOTS: OrderFormSlot[] = [
  {
    "key": "customer_name",
    "table": 1,
    "row": 0,
    "cell": 1,
    "label": "Customer Name:"
  },
  {
    "key": "company_number",
    "table": 1,
    "row": 0,
    "cell": 3,
    "label": "Company Number:"
  },
  {
    "key": "vat_number",
    "table": 1,
    "row": 1,
    "cell": 1,
    "label": "VAT Registration Number:"
  },
  {
    "key": "registered_office",
    "table": 1,
    "row": 1,
    "cell": 3,
    "label": "Registered Office Address:"
  },
  {
    "key": "representative",
    "table": 1,
    "row": 2,
    "cell": 1,
    "label": "Customer Representative:"
  },
  {
    "key": "contact_details",
    "table": 1,
    "row": 2,
    "cell": 3,
    "label": "Contact Details (including email):"
  },
  {
    "key": "order_number",
    "table": 2,
    "row": 0,
    "cell": 1,
    "label": "Order Number:"
  },
  {
    "key": "delivery_estimate",
    "table": 2,
    "row": 0,
    "cell": 3,
    "label": "Estimated Delivery Date:"
  },
  {
    "key": "mot_expiry",
    "table": 4,
    "row": 0,
    "cell": 1,
    "label": "MOT Expiry:"
  },
  {
    "key": "specification",
    "table": 4,
    "row": 1,
    "cell": 0,
    "label": "Specification & Modifications (if any):"
  },
  {
    "key": "net_price",
    "table": 4,
    "row": 2,
    "cell": 1,
    "label": "Net Price:"
  },
  {
    "key": "vat",
    "table": 4,
    "row": 3,
    "cell": 1,
    "label": "VAT:"
  },
  {
    "key": "delivery_address",
    "table": 4,
    "row": 4,
    "cell": 1,
    "label": "Delivery Address & Charges (including agreed Incoterm):"
  },
  {
    "key": "total_price",
    "table": 4,
    "row": 5,
    "cell": 1,
    "label": "Total Price (including any refurbishment):"
  },
  {
    "key": "deposit",
    "table": 4,
    "row": 6,
    "cell": 1,
    "label": "Deposit (including date received and method of payment):"
  }
];

export const SCHEDULE = {
  "table": 3,
  "headerRow": 0,
  "firstBodyRow": 1,
  "blankRows": 4,
  "columns": [
    "Trailer Manufacturer & Year",
    "Qty",
    "Chassis Number",
    "Stock Number",
    "MOT Expiry",
    "Ministry Number",
    "Condition (New or Used)",
    "Net Price Per Trailer (excl. VAT)"
  ]
} as const;

/** What a proposal leaves out: the signing page and the terms behind it. */
export const SIGNING_TABLE = 5;
export const TERMS_TABLES: number[] = [6,7];
export const TERMS_POINTER = "All Orders are subject to STC Sales and Leasing Limited’s standard terms and conditions. Please refer to the copy attached overleaf.";
export const TERMS_POINTER_MARK = "All Orders are subject to STC Sales and Leasing Limited";

export const TABLE_COUNT = 8;
