/* =============================================================
   The database's copy of what a command may write.

   `command_apply` builds UPDATE statements from names in a payload, so
   it needs a boundary it can check them against, and that boundary has
   to live in the database rather than in the caller. A caller that
   validates its own payload validates nothing: the point of the
   allowlist is to hold when something upstream is wrong.

   Generated from the canonical registry rather than typed, so the two
   cannot disagree by anybody forgetting. `npm run check:writable-columns`
   compares the emitted file with the registry and fails if they differ,
   which is what makes this a derived artefact rather than a second copy.

     npm run gen:writable-columns    writes the migration
     npm run check:writable-columns  fails if it is stale
   ============================================================= */
import { readFileSync, writeFileSync } from 'fs';
import { entities } from '../lib/command/ir/registry';
import { ROLES, capabilitiesFor } from '../lib/crm/permissions';
import type { UserRole } from '../lib/types';

const OUT = 'supabase/migrations/008_writable_columns_seed.sql';
const ROLES_OUT = 'supabase/migrations/016_capability_roles_seed.sql';

/**
 * Every table and column the canonical registry says is writable.
 *
 * From `FieldDef.writable`, which is `columns.ts` and `fields.ts`
 * agreeing. A column either dictionary calls unwritable never reaches
 * here, so the database's boundary and the application's are the same
 * boundary described twice.
 */
export function writableColumns(): { table: string; column: string }[] {
  const out: { table: string; column: string }[] = [];
  for (const e of entities()) {
    for (const f of e.fields) {
      if (!f.writable) continue;
      out.push({ table: e.table, column: f.field });
    }
  }
  /* Two entities can share a table, so the same pair can arrive twice. */
  const seen = new Set<string>();
  return out
    .filter((r) => {
      const key = `${r.table}.${r.column}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => `${a.table}.${a.column}`.localeCompare(`${b.table}.${b.column}`));
}

export function seedSql(): string {
  const rows = writableColumns();
  const values = rows
    .map((r) => `  ('${r.table}', '${r.column}')`)
    .join(',\n');

  return `-- =============================================================
-- GENERATED by \`npm run gen:writable-columns\`. Do not edit.
--
-- What \`command_apply\` will accept, derived from the canonical
-- registry: a column both \`columns.ts\` and \`fields.ts\` agree is
-- writable. \`npm run check:writable-columns\` fails if this file and
-- the registry have drifted.
--
-- Replaced wholesale rather than merged, so a column that stops being
-- writable stops being writable here too. A seed that only ever grows
-- is how a revoked permission survives in the database.
--
-- ${rows.length} columns.
-- =============================================================

BEGIN;

DELETE FROM command_writable_columns;

INSERT INTO command_writable_columns (table_name, column_name) VALUES
${values};

COMMIT;
`;
}

/* =============================================================
   Which roles hold which capability.

   The database has to be able to answer this on its own. An operation
   that only checks visibility of a record lets a viewer reach it
   straight through PostgREST and skip the command runtime entirely,
   which is exactly what `command_attach_file` did: it was granted to
   every authenticated user and asked only whether the target row could
   be seen.

   So the same permission table the application reads is seeded into the
   database, from `lib/crm/permissions.ts` rather than typed, and
   `npm run check:writable-columns` fails if the two have drifted.
   ============================================================= */

export function capabilityRoles(): { capability: string; role: string }[] {
  const out: { capability: string; role: string }[] = [];
  for (const role of ROLES) {
    for (const cap of capabilitiesFor({ role: role as UserRole })) {
      out.push({ capability: cap, role });
    }
  }
  return out.sort((a, b) =>
    `${a.capability}.${a.role}`.localeCompare(`${b.capability}.${b.role}`));
}

export function rolesSeedSql(): string {
  const rows = capabilityRoles();
  const values = rows.map((r) => `  ('${r.capability}', '${r.role}')`).join(',\n');

  return `-- =============================================================
-- GENERATED by \`npm run gen:writable-columns\`. Do not edit.
--
-- Which roles hold which capability, derived from
-- \`lib/crm/permissions.ts\`. The database needs its own copy because a
-- function granted to \`authenticated\` is reachable through PostgREST
-- without the command runtime in front of it, and a function that only
-- checks whether a row is VISIBLE lets a viewer write through it.
--
-- Replaced wholesale rather than merged, so a capability a role loses is
-- a capability it loses here too. A seed that only ever grows is how a
-- revoked permission survives in the database.
--
-- ${rows.length} pairs.
-- =============================================================

CREATE TABLE IF NOT EXISTS command_capability_roles (
  capability TEXT NOT NULL,
  role       TEXT NOT NULL,
  PRIMARY KEY (capability, role)
);

ALTER TABLE command_capability_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "command_capability_roles_read" ON command_capability_roles;
-- Readable so a check can compare it with the application. Nobody writes
-- it from the application: it is replaced wholesale by the generator.
CREATE POLICY "command_capability_roles_read" ON command_capability_roles
  FOR SELECT USING (auth.role() = 'authenticated');

-- Does the caller hold this capability? One place, so every function
-- that needs to ask gets the same answer as the application.
CREATE OR REPLACE FUNCTION command_may(p_capability TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
STABLE
AS \$fn\$
  SELECT EXISTS (
    SELECT 1 FROM command_capability_roles r
    WHERE r.capability = p_capability
      AND r.role = current_role_safe()
  )
\$fn\$;

REVOKE ALL ON FUNCTION command_may(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION command_may(TEXT) TO authenticated;

BEGIN;

DELETE FROM command_capability_roles;

INSERT INTO command_capability_roles (capability, role) VALUES
${values};

COMMIT;
`;
}

/* -------------------------------------------------------------
   Only when run directly.

   `writableColumns` is imported by the mutation check, which wants the
   allowlist and emphatically does not want a file written as a side
   effect of importing it.
   ------------------------------------------------------------- */

const invokedDirectly = process.argv[1]?.endsWith('generate-writable-columns.ts') ?? false;

if (!invokedDirectly) {
  /* Nothing to do. */
} else if (process.argv.includes('--check')) {
  let stale = false;
  for (const [file, wanted] of [[OUT, seedSql()], [ROLES_OUT, rolesSeedSql()]] as const) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      console.log(`\n  ${file} has never been generated. Run npm run gen:writable-columns\n`);
      stale = true;
      continue;
    }
    if (current !== wanted) {
      console.log(`\n  ${file} does not match the application.`);
      console.log('  Run npm run gen:writable-columns and commit the result.\n');
      stale = true;
    }
  }
  if (stale) process.exitCode = 1;
  else {
    console.log(`\n  ${writableColumns().length} writable columns and `
      + `${capabilityRoles().length} capability grants, both matching the application.\n`);
  }
} else {
  writeFileSync(OUT, seedSql());
  writeFileSync(ROLES_OUT, rolesSeedSql());
  console.log(`\n  wrote ${OUT} with ${writableColumns().length} columns`
    + ` and ${ROLES_OUT} with ${capabilityRoles().length} grants.\n`);
}
