/* =============================================================
   The database's copy of what a command may write.

   `command_apply` builds UPDATE statements from names in a payload, so
   it needs a boundary it can check them against, and that boundary has
   to live in the database rather than in the caller. A caller that
   validates its own payload validates nothing: the point of the
   allowlist is to hold when something upstream is wrong.

   Generated from the canonical registry rather than typed, so the two
   cannot disagree by anybody forgetting. `npm run check:writable-columns`
   compares the emitted file with the registry and fails if they differ,
   which is what makes this a derived artefact rather than a second copy.

     npm run gen:writable-columns    writes the migration
     npm run check:writable-columns  fails if it is stale
   ============================================================= */
import { readFileSync, writeFileSync } from 'fs';
import { entities } from '../lib/command/ir/registry';

const OUT = 'supabase/migrations/008_writable_columns_seed.sql';

/**
 * Every table and column the canonical registry says is writable.
 *
 * From `FieldDef.writable`, which is `columns.ts` and `fields.ts`
 * agreeing. A column either dictionary calls unwritable never reaches
 * here, so the database's boundary and the application's are the same
 * boundary described twice.
 */
export function writableColumns(): { table: string; column: string }[] {
  const out: { table: string; column: string }[] = [];
  for (const e of entities()) {
    for (const f of e.fields) {
      if (!f.writable) continue;
      out.push({ table: e.table, column: f.field });
    }
  }
  /* Two entities can share a table, so the same pair can arrive twice. */
  const seen = new Set<string>();
  return out
    .filter((r) => {
      const key = `${r.table}.${r.column}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => `${a.table}.${a.column}`.localeCompare(`${b.table}.${b.column}`));
}

export function seedSql(): string {
  const rows = writableColumns();
  const values = rows
    .map((r) => `  ('${r.table}', '${r.column}')`)
    .join(',\n');

  return `-- =============================================================
-- GENERATED by \`npm run gen:writable-columns\`. Do not edit.
--
-- What \`command_apply\` will accept, derived from the canonical
-- registry: a column both \`columns.ts\` and \`fields.ts\` agree is
-- writable. \`npm run check:writable-columns\` fails if this file and
-- the registry have drifted.
--
-- Replaced wholesale rather than merged, so a column that stops being
-- writable stops being writable here too. A seed that only ever grows
-- is how a revoked permission survives in the database.
--
-- ${rows.length} columns.
-- =============================================================

BEGIN;

DELETE FROM command_writable_columns;

INSERT INTO command_writable_columns (table_name, column_name) VALUES
${values};

COMMIT;
`;
}

/* -------------------------------------------------------------
   Only when run directly.

   `writableColumns` is imported by the mutation check, which wants the
   allowlist and emphatically does not want a file written as a side
   effect of importing it.
   ------------------------------------------------------------- */

const invokedDirectly = process.argv[1]?.endsWith('generate-writable-columns.ts') ?? false;

if (!invokedDirectly) {
  /* Nothing to do. */
} else if (process.argv.includes('--check')) {
  const wanted = seedSql();
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.log(`\n  ${OUT} has never been generated. Run npm run gen:writable-columns\n`);
    process.exitCode = 1;
  }
  if (current && current !== wanted) {
    console.log(`\n  ${OUT} does not match the registry.`);
    console.log('  Run npm run gen:writable-columns and commit the result.\n');
    process.exitCode = 1;
  } else if (current) {
    console.log(`\n  ${writableColumns().length} writable columns, and the seed matches the registry.\n`);
  }
} else {
  writeFileSync(OUT, seedSql());
  console.log(`\n  wrote ${OUT} with ${writableColumns().length} columns.\n`);
}
