/* =============================================================
   Read the kit's data contract, write the application's.

   From the business, about the analytics kit and true of this one:

     Your permission has been removed now to vibecode and do your own
     thing ... IM A PROFESSIONAL DESIGNER, I DESIGN FIRST THEN HAND IT
     TO YOU AND YOU PORT IT IN.

   So no number in `lib/ratecards/kit.generated.ts` is typed by hand.
   Every one of them comes out of `docs/source/rate_cards/rate-model.json`
   through this script, and `npm run check:rate-card-kit` fails if the
   generated file and the kit have drifted apart.

   ---- The one computation, and why it is not a choice ----

   The kit ships `hours` rounded to two decimals and `value2026`, the
   signed-off KNDS figure, and its header says:

     hours x POOLS[pool] reproduces value2026 exactly at the 2026 labour
     rates, so the generic template matches the signed-off KNDS card.

   That does not hold with the hours as shipped. Of the 19 derived
   rates, 3 reproduce their figure, 14 miss by between 5p and 40p, and 2
   cannot be reproduced at all because one `hours` is asked to produce
   two different per-axle prices (HGV A Service is 157.50 on two axles
   and 190.50 on three).

   The kit says which of the two is authoritative, in the same header:

     Those hours were back-calculated from it; they are the starting
     point, not gospel.

   `value2026` is the signed card. So the hours are recomputed from it,
   `value2026 / pool`, at full precision, per axle where the axles
   differ. That invents nothing: both numbers are already in the kit,
   and it is division. It also satisfies the pack's own two rules,
   "store hours, never the price" and "never round stored hours", and
   makes `hours x pool` reproduce the signed card to the penny, which is
   what the export has to do.
   ============================================================= */
import { readFileSync, writeFileSync } from 'node:fs';

const KIT = 'docs/source/rate_cards/rate-model.json';
const OUT = 'lib/ratecards/kit.generated.ts';

type Basis = 'derived' | 'labour' | 'fixed' | 'statutory' | 'tbc' | 'blank';

type KitRate = {
  section: string;
  item: string;
  basis: Basis;
  pool?: string;
  hours?: number | number[];
  axles?: number[];
  value2026?: number | number[] | string;
  perAxle?: number;
  cap?: number;
  capBy?: string;
  note?: string;
};

type Model = {
  labourPools: Record<string, number>;
  basisTypes: Record<string, string>;
  partsMarkup: { category: string; suppliedByCustomer: string; suppliedBySTC: string }[];
  fleetsmartInclusions: { inclusion: string; silver: boolean; gold: boolean; platinum: boolean }[];
  rates: KitRate[];
};

const model = JSON.parse(readFileSync(KIT, 'utf8')) as Model;
const pools = model.labourPools;

/** The signed figure, as a list the length of the priced columns. */
function signed(r: KitRate): (number | string | null)[] {
  const v = r.value2026;
  const width = r.axles ? r.axles.length : 1;
  if (Array.isArray(v)) return v as (number | string)[];
  if (v === undefined || v === null) return Array(width).fill(null);
  return Array(width).fill(v);
}

/** Hours that reproduce the signed figure exactly, per column. */
function hoursFor(r: KitRate): number[] | null {
  if (r.basis !== 'derived') return null;
  const pool = pools[r.pool!];
  if (!pool) throw new Error(`${r.item}: derived with no labour pool`);
  return signed(r).map((v) => {
    if (typeof v !== 'number') throw new Error(`${r.item}: derived from a non-numeric figure ${String(v)}`);
    return v / pool;
  });
}

const rates = model.rates.map((r, i) => ({
  id: `r${String(i + 1).padStart(2, '0')}`,
  section: r.section,
  item: r.item,
  basis: r.basis,
  pool: r.pool ?? null,
  axles: r.axles ?? null,
  hours: hoursFor(r),
  signed: signed(r),
  perAxle: r.perAxle ?? null,
  cap: r.cap ?? null,
  capBy: r.capBy ?? null,
  note: r.note ?? null,
}));

/* Prove the claim this file makes, here, at generation time, rather
   than leaving it to be believed. A derived rate whose hours do not
   reproduce its signed figure to the penny is a build failure. */
for (const r of rates) {
  if (r.basis !== 'derived') continue;
  const pool = pools[r.pool!]!;
  r.hours!.forEach((h, c) => {
    const got = Math.round(h * pool * 100) / 100;
    const want = r.signed[c];
    if (typeof want === 'number' && got !== want) {
      throw new Error(`${r.item} column ${c}: ${h} x ${pool} = ${got}, signed says ${want}`);
    }
  });
}

const body = `/* GENERATED by scripts/rate-card-generate.ts from
   docs/source/rate_cards/rate-model.json. Do not edit by hand.
   Run \`npm run rate-card:generate\` after a new kit arrives.

   ---- Two en dashes in here are deliberate ----

   'Loaded blocks – Trailers' and 'Loaded Weight trailer – Vehicles' are
   row labels copied character for character out of the signed KNDS
   workbook, where they print exactly like that. The repository's dash
   ban governs prose written for this repository; it does not govern a
   customer's document, for the same reason docs/source is exempt from
   it. Rewriting these would change what prints on a rate card a
   customer compares against last year's.

   Every number here came out of the kit. The hours are the signed
   figure divided by its labour pool, at full precision, so that
   hours x pool reproduces the signed card to the penny. See the
   script's header for why the kit's own rounded hours are not used. */

export type RateBasis = ${Object.keys(model.basisTypes).map((b) => `'${b}'`).join(' | ')};

/** What each basis means, in the kit's own words. */
export const BASIS_MEANS: Record<RateBasis, string> = ${JSON.stringify(model.basisTypes, null, 2)};

/** The five labour rates every derived rate follows. */
export const LABOUR_POOLS: Record<string, number> = ${JSON.stringify(pools, null, 2)};

export type KitRate = {
  id: string;
  section: string;
  item: string;
  basis: RateBasis;
  pool: string | null;
  /** Which axle columns are priced. Null means the single price column. */
  axles: number[] | null;
  /** Hours per priced column, full precision. Null unless derived. */
  hours: number[] | null;
  /** The signed 2026 figure per priced column. A string is 'tbc' or 'n/a'. */
  signed: (number | string | null)[];
  perAxle: number | null;
  cap: number | null;
  capBy: string | null;
  note: string | null;
};

/** All ${rates.length} rates, in the order the master workbook prints them. */
export const KIT_RATES: KitRate[] = ${JSON.stringify(rates, null, 2)};

export const PARTS_MARKUP = ${JSON.stringify(model.partsMarkup, null, 2)};

/** The ${model.fleetsmartInclusions.length} FleetSmart+ inclusions, by tier. */
export const FS_INCLUSIONS = ${JSON.stringify(model.fleetsmartInclusions, null, 2)};
`;

writeFileSync(OUT, body);

/* ---- And the same numbers as rows, for the database ----

   The FleetSmart+ builder creates a rate card from inside a database
   transaction, so the template has to be readable from there. A
   template only the browser knows cannot be read by a function.

   Generated rather than hand written for the reason migration 016 is:
   two lists of 45 rates drift within a month of being written twice. */
const SEED = 'supabase/migrations/111_rate_card_template_seed.sql';

const sq = (v: string | null) => (v === null ? 'NULL' : `'${v.replace(/'/g, "''")}'`);
const nq = (v: number | null) => (v === null ? 'NULL' : String(v));

const labourLabels: Record<string, string> = {
  trl: 'Hourly Rate - Trailers, in hours',
  trlO: 'Hourly Rate - Trailers, out of hours',
  hgv: "Hourly Rate - HGVs/LCV's, in hours",
  hgvO: "Hourly Rate - HGVs/LCV's, out of hours",
  body: 'Hourly Rate - Bodyshop, in hours',
};

const rateRows: string[] = [];
rates.forEach((r, position) => {
  /* One row per priced column. Axle 0 is a rate with a single price. */
  const columns = r.axles ?? [0];
  columns.forEach((axle, c) => {
    const signedValue = r.signed[c] ?? null;
    const isText = typeof signedValue === 'string';
    rateRows.push('  (' + [
      sq(r.id), String(r.axles ? axle : 0), sq(r.section), sq(r.item), sq(r.basis),
      r.basis === 'derived' ? nq(r.hours![c]!) : 'NULL',
      sq(r.pool),
      r.basis === 'derived' || isText || signedValue === null
        ? 'NULL' : nq(signedValue as number),
      isText ? sq(signedValue as string) : 'NULL',
      nq(r.cap), sq(r.capBy), String(position),
    ].join(', ') + ')');
  });
});

const seed = `-- =============================================================
-- 111. The rate card template, as rows.
--
-- GENERATED by scripts/rate-card-generate.ts from
-- docs/source/rate_cards/rate-model.json. Do not edit by hand.
-- Run \`npm run rate-card:generate\` after a new kit arrives and commit
-- the result; \`npm run check:rate-card-kit\` fails if they have drifted.
--
-- Every card starts as a copy of this. The hours are the signed KNDS
-- figure divided by its labour pool at full precision, so hours x pool
-- reproduces the signed card to the penny. Nothing here stores a derived
-- price, which is the rule the whole design rests on.
--
-- Safe to run twice: each of the three tables is emptied and refilled.
-- =============================================================

DELETE FROM rate_card_template_labour;
INSERT INTO rate_card_template_labour (pool, label, rate, position) VALUES
${Object.entries(pools).map(([pool, rate], i) =>
  `  (${sq(pool)}, ${sq(labourLabels[pool] ?? pool)}, ${nq(rate)}, ${i})`).join(',\n')};

DELETE FROM rate_card_template;
INSERT INTO rate_card_template
  (rate_id, axle, section, item, basis, hours, pool, amount, text_value, cap, cap_by, position) VALUES
${rateRows.join(',\n')};

DELETE FROM rate_card_inclusions;
INSERT INTO rate_card_inclusions (inclusion, silver, gold, platinum, position) VALUES
${model.fleetsmartInclusions.map((i, n) =>
  `  (${sq(i.inclusion)}, ${i.silver ? 'TRUE' : 'FALSE'}, ${i.gold ? 'TRUE' : 'FALSE'}, ${i.platinum ? 'TRUE' : 'FALSE'}, ${n})`).join(',\n')};

DO $$
DECLARE n INT; m INT; k INT;
BEGIN
  SELECT COUNT(*) INTO n FROM rate_card_template;
  SELECT COUNT(*) INTO m FROM rate_card_template_labour;
  SELECT COUNT(*) INTO k FROM rate_card_inclusions;
  RAISE NOTICE 'rate card template: % priced columns, % labour pools, % inclusions', n, m, k;
END $$;
`;
writeFileSync(SEED, seed);
console.log(`  ${rateRows.length} priced columns written to ${SEED}`);
const derived = rates.filter((r) => r.basis === 'derived').length;
console.log(`  ${rates.length} rates, ${derived} derived and every one reproducing its signed figure`);
console.log(`  ${Object.keys(pools).length} labour pools, ${model.partsMarkup.length} parts rows, ${model.fleetsmartInclusions.length} inclusions`);
console.log(`  written to ${OUT}`);
