/* =============================================================
   Read the Roles kit's variable parts out of its own files.

   The handoff in docs/source/roles_hub is shipped as written, and the
   only things this port needs to KNOW about it, rather than copy, are:

     - which class draws a coverage bar at a given percentage and tone,
       because the kit has one class per bar it happened to draw
     - which three classes carry each division's tint: the bar down a
       node, the bar beside the inspector title, the legend swatch
     - the sixteen role ids the kit wired, and the exact text of the
       three selection rules it wrote for each, so the same rules can be
       written for the real roles

   Nothing here is typed in. Every value is a regex over the kit's CSS,
   its behaviour file and its data file, and `check:roles-port` fails if
   the committed output is not what these files say now.

   Usage: tsx scripts/roles-port-generate.ts [--out path]
   ============================================================= */
import { readFileSync, writeFileSync } from 'node:fs';

const KIT = 'docs/source/roles_hub';
const OUT = process.argv.includes('--out')
  ? process.argv[process.argv.indexOf('--out') + 1]!
  : 'components/admin/roles/kit.generated.ts';

const css = readFileSync(`${KIT}/roles-page.css`, 'utf8');
const behaviour = readFileSync(`${KIT}/roles-behaviour.css`, 'utf8');
const data = JSON.parse(readFileSync(`${KIT}/roles-data.json`, 'utf8')) as {
  capabilityTotal: number;
  divisions: Record<string, { label: string; tint: string }>;
};

/* ---- Coverage bars ---- */
const fills: { cls: string; pct: number; tone: string }[] = [];
for (const m of css.matchAll(/^\.(r-[0-9a-z]+)\{display:block;width:(\d+)%;height:100%;background:var\(--(success|warning|danger)\)\}$/gm)) {
  fills.push({ cls: m[1]!, pct: Number(m[2]), tone: m[3]! });
}
fills.sort((a, b) => a.pct - b.pct || a.cls.localeCompare(b.cls));
if (fills.length === 0) throw new Error('no coverage bar classes found in roles-page.css');

/* ---- Division tints ---- */
const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const find = (re: RegExp, what: string) => {
  const m = css.match(re);
  if (!m) throw new Error(`no class for ${what}`);
  return m[1]!;
};
const divisions: Record<string, { label: string; tint: string; node: string; head: string; swatch: string }> = {};
for (const [id, d] of Object.entries(data.divisions)) {
  const hex = esc(d.tint);
  divisions[id] = {
    label: d.label,
    tint: d.tint,
    node:   find(new RegExp(`^\\.(r-[0-9a-z]+)\\{position:absolute;left:0;top:0;bottom:0;width:3px;background:${hex};`, 'm'), `${id} node bar`),
    head:   find(new RegExp(`^\\.(r-[0-9a-z]+)\\{width:4px;align-self:stretch;background:${hex};`, 'm'), `${id} inspector bar`),
    swatch: find(new RegExp(`^\\.(r-[0-9a-z]+)\\{width:8px;height:8px;border-radius:2px;background:${hex}\\}`, 'm'), `${id} swatch`),
  };
}

/* ---- Selection rules ---- */
const ids = [...new Set([...behaviour.matchAll(/^#sn-([a-z]+):checked/gm)].map((m) => m[1]!))];
if (ids.length === 0) throw new Error('no role ids in roles-behaviour.css');
const first = ids[0]!;
const rules = behaviour.split('\n')
  .filter((l) => l.startsWith(`#sn-${first}:checked`))
  /* The id appears in three places: the input's id, the panel's class
     and the row's data attribute. Replaced there and nowhere else, since
     the first id is `md` and `var(--r-md)` contains it too. */
  .map((l) => l.split(`sn-${first}`).join('sn-{id}')
    .split(`sp-${first}`).join('sp-{id}')
    .split(`data-list="${first}"`).join('data-list="{id}"'));
if (rules.length !== 3) throw new Error(`expected 3 rules per role, found ${rules.length}`);
const fill = (rule: string, id: string) => rule.split('{id}').join(id);
/* Every id must have exactly those three, or the template is a guess. */
for (const id of ids) {
  for (const r of rules) {
    if (!behaviour.includes(fill(r, id))) throw new Error(`rule missing for ${id}: ${r}`);
  }
}

const out = `/* GENERATED by scripts/roles-port-generate.ts from docs/source/roles_hub.
   Do not edit. Run \`npm run roles-port:generate\` after a new kit arrives. */

/** One class per coverage bar the kit draws: its width and its tone. */
export const FILLS = ${JSON.stringify(fills, null, 2)} as const;

/** The three classes that carry each division's tint. */
export const DIVISIONS = ${JSON.stringify(divisions, null, 2)} as const;

/** The role ids the kit wired, in the order roles-behaviour.css names them. */
export const KIT_IDS = ${JSON.stringify(ids)} as const;

/** The kit's three selection rules for one role, with {id} where the id goes. */
export const BEHAVIOUR_RULES = ${JSON.stringify(rules, null, 2)} as const;

/** The capability total the kit's placeholder data was drawn against. */
export const KIT_CAPABILITY_TOTAL = ${data.capabilityTotal};
`;
writeFileSync(OUT, out);
console.log(`  wrote ${OUT}: ${fills.length} bars, ${Object.keys(divisions).length} divisions, ${ids.length} ids`);
