-- =============================================================
-- GENERATED by `npm run gen:writable-columns`. Do not edit.
--
-- What `command_apply` will accept, derived from the canonical
-- registry: a column both `columns.ts` and `fields.ts` agree is
-- writable. `npm run check:writable-columns` fails if this file and
-- the registry have drifted.
--
-- Replaced wholesale rather than merged, so a column that stops being
-- writable stops being writable here too. A seed that only ever grows
-- is how a revoked permission survives in the database.
--
-- 86 columns.
-- =============================================================

BEGIN;

DELETE FROM command_writable_columns;

INSERT INTO command_writable_columns (table_name, column_name) VALUES
  ('calendar_events', 'all_day'),
  ('calendar_events', 'color'),
  ('calendar_events', 'description'),
  ('calendar_events', 'end_at'),
  ('calendar_events', 'start_at'),
  ('calendar_events', 'title'),
  ('calendar_events', 'visibility'),
  ('crm_contacts', 'account_manager'),
  ('crm_contacts', 'address'),
  ('crm_contacts', 'assigned_to'),
  ('crm_contacts', 'category'),
  ('crm_contacts', 'company_name'),
  ('crm_contacts', 'contact_name'),
  ('crm_contacts', 'description'),
  ('crm_contacts', 'email'),
  ('crm_contacts', 'employee_count'),
  ('crm_contacts', 'last_contact'),
  ('crm_contacts', 'location'),
  ('crm_contacts', 'notes'),
  ('crm_contacts', 'phone'),
  ('crm_contacts', 'relationship'),
  ('crm_contacts', 'services_interested'),
  ('crm_contacts', 'source'),
  ('crm_contacts', 'trailers'),
  ('crm_contacts', 'trucks'),
  ('crm_contacts', 'turnover'),
  ('crm_contacts', 'vans'),
  ('crm_contacts', 'vehicles'),
  ('social_posts', 'caption'),
  ('social_posts', 'content'),
  ('social_posts', 'hashtags'),
  ('social_posts', 'image_url'),
  ('social_posts', 'platform'),
  ('social_posts', 'reviewed_by'),
  ('social_posts', 'scheduled_date'),
  ('social_posts', 'status'),
  ('stock_trailers', 'axle_type'),
  ('stock_trailers', 'body_colour'),
  ('stock_trailers', 'category'),
  ('stock_trailers', 'chassis_colour'),
  ('stock_trailers', 'chassis_number'),
  ('stock_trailers', 'colour'),
  ('stock_trailers', 'comments'),
  ('stock_trailers', 'customer'),
  ('stock_trailers', 'deposit_received'),
  ('stock_trailers', 'description'),
  ('stock_trailers', 'dispatch_date'),
  ('stock_trailers', 'documents'),
  ('stock_trailers', 'door_type'),
  ('stock_trailers', 'expected_delivery'),
  ('stock_trailers', 'fleet_serve_link'),
  ('stock_trailers', 'hyperlink'),
  ('stock_trailers', 'jr_notes'),
  ('stock_trailers', 'location'),
  ('stock_trailers', 'make'),
  ('stock_trailers', 'ministry_no'),
  ('stock_trailers', 'model'),
  ('stock_trailers', 'month'),
  ('stock_trailers', 'mot_date'),
  ('stock_trailers', 'nbv'),
  ('stock_trailers', 'new_or_used'),
  ('stock_trailers', 'notes'),
  ('stock_trailers', 'order_date'),
  ('stock_trailers', 'paid_in_full'),
  ('stock_trailers', 'paid_status'),
  ('stock_trailers', 'quote_no'),
  ('stock_trailers', 'received_date'),
  ('stock_trailers', 'refurb_costs'),
  ('stock_trailers', 'refurb_costs_at_sale'),
  ('stock_trailers', 'refurb_done'),
  ('stock_trailers', 'refurb_update'),
  ('stock_trailers', 'retail_price'),
  ('stock_trailers', 'sales_price'),
  ('stock_trailers', 'sales_rep'),
  ('stock_trailers', 'side_aperture'),
  ('stock_trailers', 'signed_order'),
  ('stock_trailers', 'sold_price'),
  ('stock_trailers', 'status'),
  ('stock_trailers', 'status_text'),
  ('stock_trailers', 'stc_no'),
  ('stock_trailers', 'supplier'),
  ('stock_trailers', 'supplier_no'),
  ('stock_trailers', 'trade_in'),
  ('stock_trailers', 'trailer_docs'),
  ('stock_trailers', 'tread_depths'),
  ('stock_trailers', 'year');

COMMIT;
