-- =============================================================
-- GENERATED by `npm run gen:writable-columns`. Do not edit.
--
-- Which roles hold which capability, derived from
-- `lib/crm/permissions.ts`. The database needs its own copy because a
-- function granted to `authenticated` is reachable through PostgREST
-- without the command runtime in front of it, and a function that only
-- checks whether a row is VISIBLE lets a viewer write through it.
--
-- Replaced wholesale rather than merged, so a capability a role loses is
-- a capability it loses here too. A seed that only ever grows is how a
-- revoked permission survives in the database.
--
-- 134 pairs.
-- =============================================================

CREATE TABLE IF NOT EXISTS command_capability_roles (
  capability TEXT NOT NULL,
  role       TEXT NOT NULL,
  PRIMARY KEY (capability, role)
);

ALTER TABLE command_capability_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "command_capability_roles_read" ON command_capability_roles;
-- Readable so a check can compare it with the application. Nobody writes
-- it from the application: it is replaced wholesale by the generator.
CREATE POLICY "command_capability_roles_read" ON command_capability_roles
  FOR SELECT USING (auth.role() = 'authenticated');

-- Does the caller hold this capability? One place, so every function
-- that needs to ask gets the same answer as the application.
CREATE OR REPLACE FUNCTION command_may(p_capability TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
STABLE
AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM command_capability_roles r
    WHERE r.capability = p_capability
      AND r.role = current_role_safe()
  )
$fn$;

REVOKE ALL ON FUNCTION command_may(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION command_may(TEXT) TO authenticated;

-- What it takes to make one of a table's rows, or get rid of one.
-- command_apply builds DELETE statements from a payload, and a payload
-- is not a permission.
CREATE TABLE IF NOT EXISTS command_entity_permissions (
  table_name TEXT NOT NULL,
  operation  TEXT NOT NULL CHECK (operation IN ('create', 'delete', 'attach')),
  capability TEXT NOT NULL,
  PRIMARY KEY (table_name, operation)
);

-- The set of operations grows. CREATE TABLE IF NOT EXISTS leaves an
-- existing table's constraint exactly as it was, so a database migrated
-- before the attach operation existed would refuse the seed below
-- rather than the seed telling it what changed.
ALTER TABLE command_entity_permissions
  DROP CONSTRAINT IF EXISTS command_entity_permissions_operation_check;
ALTER TABLE command_entity_permissions
  ADD CONSTRAINT command_entity_permissions_operation_check
  CHECK (operation IN ('create', 'delete', 'attach'));

ALTER TABLE command_entity_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "command_entity_permissions_read" ON command_entity_permissions;
CREATE POLICY "command_entity_permissions_read" ON command_entity_permissions
  FOR SELECT USING (auth.role() = 'authenticated');

-- May the caller create or delete a row of this table? A table with no
-- row here cannot be created or deleted through the command runtime at
-- all, which is the safe way round.
CREATE OR REPLACE FUNCTION command_may_lifecycle(p_table TEXT, p_operation TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
STABLE
AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM command_entity_permissions e
    WHERE e.table_name = p_table
      AND e.operation = p_operation
      AND command_may(e.capability)
  )
$fn$;

REVOKE ALL ON FUNCTION command_may_lifecycle(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION command_may_lifecycle(TEXT, TEXT) TO authenticated;

BEGIN;

DELETE FROM command_capability_roles;

INSERT INTO command_capability_roles (capability, role) VALUES
  ('admin.audit', 'admin'),
  ('admin.settings', 'admin'),
  ('admin.users', 'admin'),
  ('compliance.sensitive', 'admin'),
  ('crm.assign', 'admin'),
  ('crm.assign', 'sales'),
  ('crm.create', 'admin'),
  ('crm.create', 'sales'),
  ('crm.delegate', 'admin'),
  ('crm.delegate', 'sales'),
  ('crm.delete', 'admin'),
  ('crm.delete', 'sales'),
  ('crm.edit', 'admin'),
  ('crm.edit', 'marketer'),
  ('crm.edit', 'sales'),
  ('crm.export', 'admin'),
  ('crm.export', 'marketer'),
  ('crm.export', 'sales'),
  ('crm.export', 'viewer'),
  ('crm.import', 'admin'),
  ('crm.import', 'sales'),
  ('crm.manageLists', 'admin'),
  ('crm.manageLists', 'sales'),
  ('crm.proposal', 'admin'),
  ('crm.proposal', 'sales'),
  ('crm.proposalForOthers', 'admin'),
  ('crm.view', 'admin'),
  ('crm.view', 'marketer'),
  ('crm.view', 'sales'),
  ('crm.view', 'viewer'),
  ('crm.viewGlobal', 'admin'),
  ('crm.viewGlobal', 'marketer'),
  ('crm.viewGlobal', 'sales'),
  ('crm.viewGlobal', 'viewer'),
  ('crm.viewOthers', 'admin'),
  ('entity.setOthers', 'admin'),
  ('entity.setOwn', 'admin'),
  ('entity.setOwn', 'marketer'),
  ('entity.setOwn', 'sales'),
  ('entity.viewAll', 'admin'),
  ('fleetsmart.build', 'admin'),
  ('fleetsmart.build', 'sales'),
  ('fleetsmart.discount', 'admin'),
  ('fleetsmart.send', 'admin'),
  ('fleetsmart.send', 'sales'),
  ('fleetsmart.view', 'admin'),
  ('fleetsmart.view', 'marketer'),
  ('fleetsmart.view', 'sales'),
  ('fleetsmart.view', 'viewer'),
  ('marketing.approve', 'admin'),
  ('marketing.edit', 'admin'),
  ('marketing.edit', 'marketer'),
  ('social.analytics', 'admin'),
  ('social.analytics', 'marketer'),
  ('social.analytics', 'sales'),
  ('social.analytics', 'viewer'),
  ('social.analyticsExport', 'admin'),
  ('social.approve', 'admin'),
  ('social.approveOwn', 'admin'),
  ('social.channels', 'admin'),
  ('social.delete', 'admin'),
  ('social.draft', 'admin'),
  ('social.draft', 'marketer'),
  ('social.editAny', 'admin'),
  ('social.editAny', 'marketer'),
  ('social.library', 'admin'),
  ('social.library', 'marketer'),
  ('social.metricSets', 'admin'),
  ('social.publishNow', 'admin'),
  ('social.schedule', 'admin'),
  ('social.schedule', 'marketer'),
  ('social.tags', 'admin'),
  ('social.tags', 'marketer'),
  ('social.templates', 'admin'),
  ('social.templates', 'marketer'),
  ('social.view', 'admin'),
  ('social.view', 'marketer'),
  ('social.view', 'sales'),
  ('social.view', 'viewer'),
  ('stock.edit', 'admin'),
  ('stock.edit', 'marketer'),
  ('stock.edit', 'sales'),
  ('work.analytics', 'admin'),
  ('work.analytics', 'marketer'),
  ('work.analytics', 'sales'),
  ('work.analytics', 'viewer'),
  ('work.analyticsAll', 'admin'),
  ('work.approve', 'admin'),
  ('work.assignDepartment', 'admin'),
  ('work.assignOthers', 'admin'),
  ('work.create', 'admin'),
  ('work.create', 'marketer'),
  ('work.create', 'sales'),
  ('work.decideRelease', 'admin'),
  ('work.delete', 'admin'),
  ('work.edit', 'admin'),
  ('work.edit', 'marketer'),
  ('work.edit', 'sales'),
  ('work.editAny', 'admin'),
  ('work.forceRelease', 'admin'),
  ('work.manageFields', 'admin'),
  ('work.manageProjects', 'admin'),
  ('work.manageSystemViews', 'admin'),
  ('work.projects', 'admin'),
  ('work.projects', 'marketer'),
  ('work.projects', 'sales'),
  ('work.projects', 'viewer'),
  ('work.publishProject', 'admin'),
  ('work.reassign', 'admin'),
  ('work.requestRelease', 'admin'),
  ('work.requestRelease', 'marketer'),
  ('work.requestRelease', 'sales'),
  ('work.requestRelease', 'viewer'),
  ('work.review', 'admin'),
  ('work.review', 'marketer'),
  ('work.rollback', 'admin'),
  ('work.schedule', 'admin'),
  ('work.setDue', 'admin'),
  ('work.shareViews', 'admin'),
  ('work.shareViews', 'marketer'),
  ('work.shareViews', 'sales'),
  ('work.view', 'admin'),
  ('work.view', 'marketer'),
  ('work.view', 'sales'),
  ('work.view', 'viewer'),
  ('work.viewAll', 'admin'),
  ('work.viewDepartment', 'admin'),
  ('work.viewDepartment', 'marketer'),
  ('work.viewDepartment', 'sales'),
  ('work.viewDepartment', 'viewer'),
  ('work.views', 'admin'),
  ('work.views', 'marketer'),
  ('work.views', 'sales'),
  ('work.views', 'viewer');

DELETE FROM command_entity_permissions;

INSERT INTO command_entity_permissions (table_name, operation, capability) VALUES
  ('calendar_events', 'create', 'crm.delegate'),
  ('calendar_events', 'delete', 'crm.delegate'),
  ('contact_addresses', 'create', 'crm.edit'),
  ('contact_addresses', 'delete', 'crm.edit'),
  ('contact_notes', 'create', 'crm.edit'),
  ('contact_notes', 'delete', 'crm.edit'),
  ('crm_contacts', 'attach', 'crm.edit'),
  ('crm_contacts', 'create', 'crm.create'),
  ('crm_contacts', 'delete', 'crm.delete'),
  ('crm_leads', 'attach', 'crm.edit'),
  ('crm_leads', 'create', 'crm.create'),
  ('crm_leads', 'delete', 'crm.delete'),
  ('crm_lists', 'create', 'crm.manageLists'),
  ('crm_lists', 'delete', 'crm.manageLists'),
  ('social_posts', 'delete', 'marketing.edit'),
  ('stock_trailers', 'attach', 'stock.edit'),
  ('stock_trailers', 'create', 'stock.edit'),
  ('stock_trailers', 'delete', 'stock.edit');

COMMIT;
