-- =============================================================
-- 111. The rate card template, as rows.
--
-- GENERATED by scripts/rate-card-generate.ts from
-- docs/source/rate_cards/rate-model.json. Do not edit by hand.
-- Run `npm run rate-card:generate` after a new kit arrives and commit
-- the result; `npm run check:rate-card-kit` fails if they have drifted.
--
-- Every card starts as a copy of this. The hours are the signed KNDS
-- figure divided by its labour pool at full precision, so hours x pool
-- reproduces the signed card to the penny. Nothing here stores a derived
-- price, which is the rule the whole design rests on.
--
-- Safe to run twice: each of the three tables is emptied and refilled.
-- =============================================================

DELETE FROM rate_card_template_labour;
INSERT INTO rate_card_template_labour (pool, label, rate, position) VALUES
  ('hgv', 'Hourly Rate - HGVs/LCV''s, in hours', 85, 0),
  ('hgvO', 'Hourly Rate - HGVs/LCV''s, out of hours', 96, 1),
  ('trl', 'Hourly Rate - Trailers, in hours', 70, 2),
  ('trlO', 'Hourly Rate - Trailers, out of hours', 83, 3),
  ('body', 'Hourly Rate - Bodyshop, in hours', 70, 4);

DELETE FROM rate_card_template;
INSERT INTO rate_card_template
  (rate_id, axle, section, item, basis, hours, pool, amount, text_value, cap, cap_by, position) VALUES
  ('r01', 1, 'Hourly Rate - Trailers', 'In hours', 'labour', NULL, 'trl', 70, NULL, NULL, NULL, 0),
  ('r01', 2, 'Hourly Rate - Trailers', 'In hours', 'labour', NULL, 'trl', 70, NULL, NULL, NULL, 0),
  ('r01', 3, 'Hourly Rate - Trailers', 'In hours', 'labour', NULL, 'trl', 70, NULL, NULL, NULL, 0),
  ('r01', 4, 'Hourly Rate - Trailers', 'In hours', 'labour', NULL, 'trl', 70, NULL, NULL, NULL, 0),
  ('r02', 1, 'Hourly Rate - Trailers', 'Out of Hours', 'labour', NULL, 'trlO', 83, NULL, NULL, NULL, 1),
  ('r02', 2, 'Hourly Rate - Trailers', 'Out of Hours', 'labour', NULL, 'trlO', 83, NULL, NULL, NULL, 1),
  ('r02', 3, 'Hourly Rate - Trailers', 'Out of Hours', 'labour', NULL, 'trlO', 83, NULL, NULL, NULL, 1),
  ('r02', 4, 'Hourly Rate - Trailers', 'Out of Hours', 'labour', NULL, 'trlO', 83, NULL, NULL, NULL, 1),
  ('r03', 0, 'Hourly Rate - HGVs/LCV''s', 'In hours', 'labour', NULL, 'hgv', 85, NULL, NULL, NULL, 2),
  ('r04', 0, 'Hourly Rate - HGVs/LCV''s', 'Out of Hours', 'labour', NULL, 'hgvO', 96, NULL, NULL, NULL, 3),
  ('r05', 0, 'Hourly Rate - Bodyshop', 'In hours', 'labour', NULL, 'body', 70, NULL, NULL, NULL, 4),
  ('r06', 0, 'Callout/Travel Rates', 'In hours', 'fixed', NULL, NULL, NULL, 'n/a', NULL, NULL, 5),
  ('r07', 0, 'Callout/Travel Rates', 'Out of Hours', 'fixed', NULL, NULL, 50, NULL, NULL, NULL, 6),
  ('r08', 0, 'Callout/Travel Rates', 'Mileage Charge', 'fixed', NULL, NULL, 1.5, NULL, NULL, NULL, 7),
  ('r09', 0, 'Callout/Travel Rates', 'C&D', 'tbc', NULL, NULL, NULL, NULL, NULL, NULL, 8),
  ('r10', 1, 'Service Rates', 'Trailer Service/Inspection', 'derived', 1.2, 'trl', NULL, NULL, NULL, NULL, 9),
  ('r10', 2, 'Service Rates', 'Trailer Service/Inspection', 'derived', 1.2, 'trl', NULL, NULL, NULL, NULL, 9),
  ('r10', 3, 'Service Rates', 'Trailer Service/Inspection', 'derived', 1.2, 'trl', NULL, NULL, NULL, NULL, 9),
  ('r10', 4, 'Service Rates', 'Trailer Service/Inspection', 'derived', 1.2, 'trl', NULL, NULL, NULL, NULL, 9),
  ('r11', 0, 'Service Rates', 'Van Engine Service (up to 3.5 ton)', 'derived', 1.4470588235294117, 'hgv', NULL, NULL, NULL, NULL, 10),
  ('r12', 2, 'Service Rates', 'Van A Service & Inspection (up to 3.5 ton)', 'derived', 1.8529411764705883, 'hgv', NULL, NULL, NULL, NULL, 11),
  ('r13', 2, 'Service Rates', 'Van B Service & Inspection (up to 3.5 ton)', 'tbc', NULL, NULL, NULL, NULL, NULL, NULL, 12),
  ('r14', 2, 'Service Rates', 'HGV 7.5 ton+ A Service & Inspection', 'derived', 1.8529411764705883, 'hgv', NULL, NULL, NULL, NULL, 13),
  ('r14', 3, 'Service Rates', 'HGV 7.5 ton+ A Service & Inspection', 'derived', 2.2411764705882353, 'hgv', NULL, NULL, NULL, NULL, 13),
  ('r15', 2, 'Service Rates', 'HGV 7.5 ton+ B Service & Inspection', 'derived', 3.1294117647058823, 'hgv', NULL, NULL, NULL, NULL, 14),
  ('r15', 3, 'Service Rates', 'HGV 7.5 ton+ B Service & Inspection', 'derived', 3.376470588235294, 'hgv', NULL, NULL, NULL, NULL, 14),
  ('r16', 2, 'Service Rates', 'HGV 7.5 ton+ C Service & Inspection', 'tbc', NULL, NULL, NULL, NULL, NULL, NULL, 15),
  ('r16', 3, 'Service Rates', 'HGV 7.5 ton+ C Service & Inspection', 'tbc', NULL, NULL, NULL, NULL, NULL, NULL, 15),
  ('r17', 0, 'Service Rates', 'Digital Tacho', 'derived', 1.3625882352941177, 'hgv', NULL, NULL, NULL, NULL, 16),
  ('r18', 0, 'Service Rates', 'Smart Tacho', 'derived', 1.6125882352941177, 'hgv', NULL, NULL, NULL, NULL, 17),
  ('r19', 0, 'Service Rates', 'Tail Lift LOLER & Weight Test (Vehicle)', 'derived', 2.070588235294118, 'hgv', NULL, NULL, NULL, NULL, 18),
  ('r20', 0, 'Service Rates', 'Tail Lift LOLER (Vehicle)', 'derived', 1.0235294117647058, 'hgv', NULL, NULL, NULL, NULL, 19),
  ('r21', 1, 'Service Rates', 'Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 20),
  ('r21', 2, 'Service Rates', 'Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 20),
  ('r21', 3, 'Service Rates', 'Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 20),
  ('r21', 4, 'Service Rates', 'Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 20),
  ('r22', 0, 'Service Rates', 'Consumables', 'fixed', NULL, NULL, 7.9, NULL, NULL, NULL, 21),
  ('r23', 0, 'Service Rates', 'Grease & Lubricants', 'fixed', NULL, NULL, 4.9, NULL, NULL, NULL, 22),
  ('r24', 0, 'MOT Fees', 'Submit for MOT at Hyde', 'derived', 1.6470588235294117, 'hgv', NULL, NULL, NULL, NULL, 23),
  ('r25', 0, 'MOT Fees', 'Submit for MOT elsewhere', 'derived', 1.6470588235294117, 'hgv', NULL, NULL, NULL, NULL, 24),
  ('r26', 0, 'MOT Fees', 'Van Steam Clean', 'derived', 0.7647058823529411, 'hgv', NULL, NULL, NULL, NULL, 25),
  ('r27', 2, 'MOT Fees', 'HGV Steam Clean', 'derived', 1, 'hgv', NULL, NULL, NULL, NULL, 26),
  ('r27', 3, 'MOT Fees', 'HGV Steam Clean', 'derived', 1, 'hgv', NULL, NULL, NULL, NULL, 26),
  ('r27', 4, 'MOT Fees', 'HGV Steam Clean', 'derived', 1, 'hgv', NULL, NULL, NULL, NULL, 26),
  ('r28', 1, 'MOT Fees', 'Trailer Steam Clean', 'derived', 1.0714285714285714, 'trl', NULL, NULL, NULL, NULL, 27),
  ('r28', 2, 'MOT Fees', 'Trailer Steam Clean', 'derived', 1.0714285714285714, 'trl', NULL, NULL, NULL, NULL, 27),
  ('r28', 3, 'MOT Fees', 'Trailer Steam Clean', 'derived', 1.0714285714285714, 'trl', NULL, NULL, NULL, NULL, 27),
  ('r28', 4, 'MOT Fees', 'Trailer Steam Clean', 'derived', 1.0714285714285714, 'trl', NULL, NULL, NULL, NULL, 27),
  ('r29', 1, 'MOT Fees', 'Brake Test', 'fixed', NULL, NULL, 18, NULL, NULL, NULL, 28),
  ('r29', 2, 'MOT Fees', 'Brake Test', 'fixed', NULL, NULL, 36, NULL, NULL, NULL, 28),
  ('r29', 3, 'MOT Fees', 'Brake Test', 'fixed', NULL, NULL, 54, NULL, NULL, NULL, 28),
  ('r29', 4, 'MOT Fees', 'Brake Test', 'fixed', NULL, NULL, 72, NULL, NULL, NULL, 28),
  ('r30', 0, 'MOT Fees', 'Headlamp Test', 'derived', 0.5294117647058824, 'hgv', NULL, NULL, NULL, NULL, 29),
  ('r31', 1, 'MOT Fees', 'Trailer Test Fee', 'statutory', NULL, NULL, 41, NULL, NULL, NULL, 30),
  ('r31', 2, 'MOT Fees', 'Trailer Test Fee', 'statutory', NULL, NULL, 54, NULL, NULL, NULL, 30),
  ('r31', 3, 'MOT Fees', 'Trailer Test Fee', 'statutory', NULL, NULL, 64, NULL, NULL, NULL, 30),
  ('r31', 4, 'MOT Fees', 'Trailer Test Fee', 'statutory', NULL, NULL, 64, NULL, NULL, NULL, 30),
  ('r32', 1, 'MOT Fees', 'Trailer Retest Fee (within 14 days)', 'statutory', NULL, NULL, 18, NULL, NULL, NULL, 31),
  ('r32', 2, 'MOT Fees', 'Trailer Retest Fee (within 14 days)', 'statutory', NULL, NULL, 25, NULL, NULL, NULL, 31),
  ('r32', 3, 'MOT Fees', 'Trailer Retest Fee (within 14 days)', 'statutory', NULL, NULL, 33, NULL, NULL, NULL, 31),
  ('r32', 4, 'MOT Fees', 'Trailer Retest Fee (within 14 days)', 'statutory', NULL, NULL, 33, NULL, NULL, NULL, 31),
  ('r33', 0, 'MOT Fees', 'Trailer Lane Fee', 'statutory', NULL, NULL, 50, NULL, 50, 'DVSA', 32),
  ('r34', 2, 'MOT Fees', 'HGV Test Fee', 'statutory', NULL, NULL, 91, NULL, NULL, NULL, 33),
  ('r34', 3, 'MOT Fees', 'HGV Test Fee', 'statutory', NULL, NULL, 113, NULL, NULL, NULL, 33),
  ('r34', 4, 'MOT Fees', 'HGV Test Fee', 'statutory', NULL, NULL, 137, NULL, NULL, NULL, 33),
  ('r35', 2, 'MOT Fees', 'HGV Retest Fee (within 14 days)', 'statutory', NULL, NULL, 35, NULL, NULL, NULL, 34),
  ('r35', 3, 'MOT Fees', 'HGV Retest Fee (within 14 days)', 'statutory', NULL, NULL, 49, NULL, NULL, NULL, 34),
  ('r35', 4, 'MOT Fees', 'HGV Retest Fee (within 14 days)', 'statutory', NULL, NULL, 65, NULL, NULL, NULL, 34),
  ('r36', 0, 'MOT Fees', 'HGV Lane Fee', 'statutory', NULL, NULL, 70, NULL, 70, 'DVSA', 35),
  ('r37', 0, 'MOT Fees', 'Loaded blocks – Trailers', 'blank', NULL, NULL, NULL, NULL, NULL, NULL, 36),
  ('r38', 0, 'MOT Fees', 'Loaded Weight trailer – Vehicles', 'fixed', NULL, NULL, 50, NULL, NULL, NULL, 37),
  ('r39', 1, 'MOT Fees', 'Hire of Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 38),
  ('r39', 2, 'MOT Fees', 'Hire of Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 38),
  ('r39', 3, 'MOT Fees', 'Hire of Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 38),
  ('r39', 4, 'MOT Fees', 'Hire of Weights', 'fixed', NULL, NULL, 100, NULL, NULL, NULL, 38),
  ('r40', 0, 'MOT Fees', 'Out of area submit for MOT', 'derived', 2.823529411764706, 'hgv', NULL, NULL, NULL, NULL, 39),
  ('r41', 0, 'MOT Fees', 'Warm brakes for MOT', 'derived', 0.5, 'hgv', NULL, NULL, NULL, NULL, 40),
  ('r42', 0, 'MOT Fees', 'Smoke Test', 'derived', 0.5882352941176471, 'hgv', NULL, NULL, NULL, NULL, 41),
  ('r43', 0, 'Tacho Costs', 'DTCO Calibration', 'derived', 1.3625882352941177, 'hgv', NULL, NULL, NULL, NULL, 42),
  ('r44', 0, 'Tacho Costs', 'Buffer Battery', 'fixed', NULL, NULL, 15.82, NULL, NULL, NULL, 43),
  ('r45', 0, 'Tacho Costs', 'Submit for Tacho', 'blank', NULL, NULL, NULL, NULL, NULL, NULL, 44);

DELETE FROM rate_card_inclusions;
INSERT INTO rate_card_inclusions (inclusion, silver, gold, platinum, position) VALUES
  ('MOT Inspection', TRUE, TRUE, TRUE, 0),
  ('Laden RBT (vehicles 4/yr, trailers 1/yr, vans n/a)', TRUE, TRUE, TRUE, 1),
  ('MOT Steamclean', TRUE, TRUE, TRUE, 2),
  ('MOT Submission', TRUE, TRUE, TRUE, 3),
  ('MOT Brake Test', TRUE, TRUE, TRUE, 4),
  ('MOT Smoke Test', TRUE, TRUE, TRUE, 5),
  ('MOT Test Fee', TRUE, TRUE, TRUE, 6),
  ('MOT Lane Fee', TRUE, TRUE, TRUE, 7),
  ('Headlamp Alignment', TRUE, TRUE, TRUE, 8),
  ('Weight Hire', TRUE, TRUE, TRUE, 9),
  ('2 Year Tacho', TRUE, TRUE, TRUE, 10),
  ('Digital compliance storage', TRUE, TRUE, TRUE, 11),
  ('Defect Reporting', TRUE, TRUE, TRUE, 12),
  ('Maintenance Scheduling', TRUE, TRUE, TRUE, 13),
  ('A Service every inspection', FALSE, TRUE, TRUE, 14),
  ('C Service, Annually', FALSE, TRUE, TRUE, 15),
  ('Fluid Level Checks', FALSE, TRUE, TRUE, 16),
  ('Grease and Lube', FALSE, TRUE, TRUE, 17),
  ('Engine Oil Top Up', FALSE, TRUE, TRUE, 18),
  ('Bulb Replacement (up to 3 bulbs, excl. H/L & DRL)', FALSE, TRUE, TRUE, 19),
  ('Customer compliance portal access', FALSE, TRUE, TRUE, 20),
  ('Tail Lift LOLER, Weight Test & Servicing', FALSE, FALSE, TRUE, 21),
  ('Brakes & suspension R&M inc', FALSE, FALSE, TRUE, 22);

DO $$
DECLARE n INT; m INT; k INT;
BEGIN
  SELECT COUNT(*) INTO n FROM rate_card_template;
  SELECT COUNT(*) INTO m FROM rate_card_template_labour;
  SELECT COUNT(*) INTO k FROM rate_card_inclusions;
  RAISE NOTICE 'rate card template: % priced columns, % labour pools, % inclusions', n, m, k;
END $$;
