/* GENERATED by scripts/roles-port-generate.ts from docs/source/roles_hub.
   Do not edit. Run `npm run roles-port:generate` after a new kit arrives. */

/** One class per coverage bar the kit draws: its width and its tone. */
export const FILLS = [
  {
    "cls": "r-6a",
    "pct": 11,
    "tone": "success"
  },
  {
    "cls": "r-67",
    "pct": 13,
    "tone": "success"
  },
  {
    "cls": "r-68",
    "pct": 14,
    "tone": "success"
  },
  {
    "cls": "r-66",
    "pct": 16,
    "tone": "success"
  },
  {
    "cls": "r-69",
    "pct": 17,
    "tone": "success"
  },
  {
    "cls": "r-2u",
    "pct": 18,
    "tone": "success"
  },
  {
    "cls": "r-2t",
    "pct": 19,
    "tone": "success"
  },
  {
    "cls": "r-2e",
    "pct": 20,
    "tone": "success"
  },
  {
    "cls": "r-2x",
    "pct": 22,
    "tone": "success"
  },
  {
    "cls": "r-2w",
    "pct": 23,
    "tone": "success"
  },
  {
    "cls": "r-6f",
    "pct": 24,
    "tone": "success"
  },
  {
    "cls": "r-3s",
    "pct": 25,
    "tone": "success"
  },
  {
    "cls": "r-28",
    "pct": 27,
    "tone": "success"
  },
  {
    "cls": "r-6c",
    "pct": 28,
    "tone": "success"
  },
  {
    "cls": "r-2y",
    "pct": 29,
    "tone": "success"
  },
  {
    "cls": "r-2d",
    "pct": 32,
    "tone": "success"
  },
  {
    "cls": "r-2r",
    "pct": 33,
    "tone": "success"
  },
  {
    "cls": "r-2v",
    "pct": 35,
    "tone": "success"
  },
  {
    "cls": "r-3r",
    "pct": 36,
    "tone": "success"
  },
  {
    "cls": "r-2c",
    "pct": 39,
    "tone": "success"
  },
  {
    "cls": "r-27",
    "pct": 40,
    "tone": "success"
  },
  {
    "cls": "r-2h",
    "pct": 41,
    "tone": "success"
  },
  {
    "cls": "r-2z",
    "pct": 42,
    "tone": "success"
  },
  {
    "cls": "r-6b",
    "pct": 43,
    "tone": "success"
  },
  {
    "cls": "r-6d",
    "pct": 44,
    "tone": "success"
  },
  {
    "cls": "r-2s",
    "pct": 45,
    "tone": "success"
  },
  {
    "cls": "r-26",
    "pct": 46,
    "tone": "warning"
  },
  {
    "cls": "r-6e",
    "pct": 47,
    "tone": "warning"
  },
  {
    "cls": "r-25",
    "pct": 50,
    "tone": "warning"
  },
  {
    "cls": "r-63",
    "pct": 52,
    "tone": "warning"
  },
  {
    "cls": "r-3v",
    "pct": 54,
    "tone": "warning"
  },
  {
    "cls": "r-2p",
    "pct": 55,
    "tone": "warning"
  },
  {
    "cls": "r-61",
    "pct": 56,
    "tone": "warning"
  },
  {
    "cls": "r-3u",
    "pct": 58,
    "tone": "warning"
  },
  {
    "cls": "r-3o",
    "pct": 59,
    "tone": "warning"
  },
  {
    "cls": "r-2o",
    "pct": 60,
    "tone": "warning"
  },
  {
    "cls": "r-5z",
    "pct": 65,
    "tone": "warning"
  },
  {
    "cls": "r-65",
    "pct": 67,
    "tone": "warning"
  },
  {
    "cls": "r-3m",
    "pct": 68,
    "tone": "warning"
  },
  {
    "cls": "r-64",
    "pct": 69,
    "tone": "warning"
  },
  {
    "cls": "r-5u",
    "pct": 71,
    "tone": "warning"
  },
  {
    "cls": "r-5x",
    "pct": 72,
    "tone": "warning"
  },
  {
    "cls": "r-3n",
    "pct": 73,
    "tone": "warning"
  },
  {
    "cls": "r-60",
    "pct": 75,
    "tone": "warning"
  },
  {
    "cls": "r-3l",
    "pct": 80,
    "tone": "warning"
  },
  {
    "cls": "r-5t",
    "pct": 82,
    "tone": "danger"
  },
  {
    "cls": "r-3k",
    "pct": 83,
    "tone": "danger"
  },
  {
    "cls": "r-3i",
    "pct": 84,
    "tone": "danger"
  },
  {
    "cls": "r-3j",
    "pct": 86,
    "tone": "danger"
  },
  {
    "cls": "r-5v",
    "pct": 92,
    "tone": "danger"
  },
  {
    "cls": "r-5y",
    "pct": 95,
    "tone": "danger"
  },
  {
    "cls": "r-5w",
    "pct": 96,
    "tone": "danger"
  },
  {
    "cls": "r-20",
    "pct": 100,
    "tone": "danger"
  }
] as const;

/** The three classes that carry each division's tint. */
export const DIVISIONS = {
  "stc": {
    "label": "STC Service",
    "tint": "#09163A",
    "node": "r-2j",
    "head": "r-2q",
    "swatch": "r-36"
  },
  "sales": {
    "label": "Trailer Sales",
    "tint": "#B31F14",
    "node": "r-3e",
    "head": "r-3q",
    "swatch": "r-37"
  },
  "hire": {
    "label": "Rentals",
    "tint": "#C77A06",
    "node": "r-3f",
    "head": "r-3t",
    "swatch": "r-38"
  },
  "grp": {
    "label": "Group",
    "tint": "#2B3F78",
    "node": "r-21",
    "head": "r-23",
    "swatch": "r-35"
  },
  "sys": {
    "label": "System",
    "tint": "#5B5B56",
    "node": "r-2g",
    "head": "r-3w",
    "swatch": "r-39"
  }
} as const;

/** The role ids the kit wired, in the order roles-behaviour.css names them. */
export const KIT_IDS = ["md","opsdir","comdir","depot","ctrl","tech","salesmgr","salesex","hiremgr","hiredesk","fsam","fin","comp","compadm","sysadmin","auditor"] as const;

/** The kit's three selection rules for one role, with {id} where the id goes. */
export const BEHAVIOUR_RULES = [
  "#sn-{id}:checked~.sn-body .sp-{id}{display:flex}",
  "#sn-{id}:checked~.sn-body label[for=\"sn-{id}\"]{outline:2px solid var(--accent);outline-offset:2px;border-radius:var(--r-md)}",
  "#sn-{id}:checked~.sn-body [data-list=\"{id}\"]{background:var(--bg-subtle);border-left-color:var(--accent);font-weight:600}"
] as const;

/** The capability total the kit's placeholder data was drawn against. */
export const KIT_CAPABILITY_TOTAL = 148;
